packages/ui/fe-bundle/tailwind.config.js
=> Change `text-muted-dark` to a lighter color

packages/fdr-sdk/src/navigation/ApiDefinitionPruner.ts, packages/fdr-sdk/src/navigation/ApiTypeIdVisitor.ts, packages/ui/app/src/api-reference/ApiEndpointPage.tsx, packages/ui/app/src/api-reference/ApiReferencePage.tsx, packages/ui/app/src/api-reference/SingleApiPageContent.tsx, packages/ui/app/src/playground/PlaygroundDrawer.tsx, packages/ui/app/src/playground/PlaygroundEndpointSelectorContent.tsx, packages/ui/app/src/resolver/ApiDefinitionResolver.ts, packages/ui/app/src/resolver/ApiEndpointResolver.ts, packages/ui/app/src/resolver/ResolvedPath.ts, packages/ui/app/src/util/convertNavigatableToResolvedPath.ts
Reduce bundle size that was accidentally increased by https://github.com/fern-api/fern-platform/pull/1379
=> chore: reduce bundle size

.github/workflows/deploy-fern-bot-dev.yml, .github/workflows/deploy-fern-bot-prod.yml, .github/workflows/invoke-fern-bot-update-spec.yml, .github/workflows/invoke-fern-bot-upgrade-generators.yml
Moves compile into separate step. 
Makes it easier to see how much time is being taken up by compile. 
N/A
=> chore(fern-bot): move compiles steps into separate step

.github/workflows/production.yml, packages/ui/app/src/analytics/posthog.ts, packages/ui/docs-bundle/.env-cmdrc.cjs
Posthog is still not firing on `uploadcare.com/docs`. This PR 
- enables debug mode in posthog
- switches to always use `NEXT_PUBLIC_` prefix for the posthog api key in the codebase
- sets the api_host config if it's changed.
=> fix: init posthog and set the api host

.github/workflows/invoke-fern-bot-update-spec.yml, .github/workflows/invoke-fern-bot-upgrade-generators.yml, servers/fern-bot/src/functions/generator-updates/shared/updateGeneratorInternal.ts
Before: https://github.com/fern-api/fern-bot-tests/pull/86 (see de-dented code block, etc.)
After: https://github.com/fern-api/fern-bot-tests/pull/91
=> chore(fern-bot): update formatting to appropriately render bullet contents

packages/ui/app/src/atoms/docs.ts, packages/ui/app/src/atoms/types.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/feature-flags.ts, packages/ui/docs-bundle/src/utils/getDocsPageProps.ts
if `is404PageHidden=true`, default to legacy behavior (redirect to the home page)
=> fix: feature flag 404 redirecting to home

packages/ui/app/src/mdx/__test__/rehypeFernCode.test.ts, packages/ui/app/src/mdx/plugins/rehypeFernCode.ts, packages/ui/app/src/syntax-highlighting/FernSyntaxHighlighter.tsx, packages/ui/app/src/syntax-highlighting/FernSyntaxHighlighterTokens.tsx, packages/ui/app/src/syntax-highlighting/FernSyntaxHighlighterTokensVirtualized.tsx
when adding `wordWrap` to the metastring, it will enable word wrapping in the code block.
=> feat: enable word wrapping in code block

packages/ui/app/src/api-reference/examples/CodeSnippetExample.tsx, packages/ui/app/src/playground/PlaygroundEndpointContent.tsx
Reverts fern-api/fern-platform#1428
=> Revert "fix: scroll to top when switching between code examples"

.github/workflows/publish-fdr-postman.yml, fern/apis/fdr/generators.yml
Setup publish job for postman generator
Dogfooding postman generator
Tested locally
=> feat(fdr): publish postman collection

packages/ui/app/src/mdx/MdxContent.tsx
Before:
https://github.com/user-attachments/assets/25f83c88-b3d1-49a5-b603-2bc5e029856b
After:
https://github.com/user-attachments/assets/e2bafb83-5713-4b21-9c95-eb2803b13d42
=> fix: markdown memoization should not prevent state change

packages/ui/docs-bundle/src/middleware.ts
https://github.com/fern-api/fern-platform/pull/1453 accidentally removed the posthog proxy
=> fix: posthog rewrite

packages/ui/app/src/api-reference/ApiEndpointPage.tsx, packages/ui/app/src/changelog/ChangelogContentLayout.tsx, packages/ui/app/src/changelog/ChangelogEntryPage.tsx, packages/ui/app/src/changelog/ChangelogPage.tsx, packages/ui/app/src/components/BottomNavigationButton.tsx, packages/ui/app/src/components/BottomNavigationButtons.tsx, packages/ui/app/src/components/BottomNavigationNeighbors.tsx, packages/ui/app/src/mdx/components/layout/GuideLayout.tsx
Implements pagination on the long-scrolling changelog page
=> fix: paginated changelog

packages/fdr-sdk/src/navigation/types/NavigationNodePage.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts, packages/ui/docs-bundle/src/utils/getDocsPageProps.ts
Reverts fern-api/fern-platform#1468
=> Revert "fix: turn off isr for redirects"

packages/fdr-sdk/src/navigation/types/NavigationNodePage.ts, packages/ui/docs-bundle/src/middleware.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all.ts, packages/ui/docs-bundle/src/utils/getDocsPageProps.ts
second attempt at https://github.com/fern-api/fern-platform/pull/1470
=> fix: turn off revalidation for redirects and 404

servers/fern-bot/src/functions/generator-updates/shared/updateGeneratorInternal.ts
Fixes FER-3259
This PR makes it so that when we check out an existing upgrade branch we now force reset it to the default branch
The idea was to make it so that we always replay the migration, ideally if we rerelease a version with a corrected migration, fern-bot runs through that upgrade as if it was the first time to take the new (corrected) migration
The ETE tests we have
=> chore(fern-bot): reset upgrade branch to default branch before upgrade

fern/fern.config.json, servers/fdr/fern/fern.config.json
Seeing the same issues as reported a few times: https://github.com/fern-api/fern-platform/actions/runs/10908259688/job/30273815629
=> chore: update fern versions to get through error

packages/fdr-sdk/package.json, packages/ui/app/src/search/SearchHits.tsx, servers/fdr/src/__test__/unit-tests/generate-algolia-search-records/__snapshots__/testGenerateAlgoliaSearchRecordsForDocs.test.ts.snap, servers/fdr/src/services/algolia/AlgoliaSearchRecordGenerator.ts
=> fix: remove import statements to unblock FDR deploy

packages/ui/app/src/atoms/sidebar.ts
- Changes errant boolean logic
- Hume incident
=> hotfix: force enable sidebar with no header

fern/apis/fdr/definition/git.yml, packages/fdr-sdk/src/client/generated/api/resources/git/client/Client.ts, packages/fdr-sdk/src/client/generated/api/resources/git/client/requests/ListPullRequestsRequest.ts, servers/fdr/prisma/migrations/20240919231438_add_author_login/migration.sql, servers/fdr/prisma/schema.prisma, servers/fdr/src/__test__/local/db/gitDao.test.ts, servers/fdr/src/api/generated/api/resources/git/service/GitService.d.ts, servers/fdr/src/controllers/git/getGitController.ts, servers/fdr/src/db/git/GitDao.ts
Adds additional filters to the list PRs endpoint, to be used by fern-bot
=> feat(fdr): add additional filters to PRs endpoint

packages/ui/app/src/playground/endpoint/PlaygroundEndpointSelectorContent.tsx, packages/ui/app/src/playground/utils/__test__/breadcrumb.test.ts, packages/ui/app/src/playground/utils/breadcrumb.ts
Moves breadcrumb trimmer into a generic utility function with tests.
=> test: breadcrumb trimmer

packages/ui/app/package.json, packages/ui/app/src/hooks/useApiRoute.ts, packages/ui/app/src/mdx/components/index.tsx, packages/ui/app/src/mdx/components/launchdarkly/LaunchDarkly.tsx, packages/ui/app/src/mdx/components/launchdarkly/index.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/integrations/launchdarkly.ts, pnpm-lock.yaml, tests/launchdarkly/fern/docs.yml, tests/launchdarkly/fern/fern.config.json, tests/launchdarkly/fern/test.mdx
Usage:
```mdx
<LaunchDarkly flag="flag-2">
Content that you want to hide.
</LaunchDarkly>
```
Preview: https://app-devbuildwithfern-b4wzy1rrh-buildwithfern.vercel.app/api/fern-docs/preview?host=launchdarkly-test.docs.dev.buildwithfern.com
Turn this flag on/off: https://app.launchdarkly.com/projects/default/flags/flag-2/targeting?env=test&selected-env=test
This PR demonstrates ability to turn flag off/on (and subscribe to updates) but does not identify the user.
=> feat: launch darkly markdown component

servers/fdr/src/__test__/unit-tests/generate-algolia-search-records/__snapshots__/testGenerateAlgoliaSearchRecordsForDocs.test.ts.snap, servers/fdr/src/services/algolia/AlgoliaSearchRecordGeneratorV2.ts
- Removes duplicated breadcrumb
- Breadcrumbs were duplicating
- Push to FDR
=> fix: remove duplicated breadcrumb from page record

packages/ui/app/src/util/resolveDocsContent.ts, pnpm-lock.yaml
See if we can get Pinecone components resolving with this change, will test on dev.
=> fix: docs bundles mdx against all other pages

pnpm-lock.yaml, tsconfig.json
=> remove docs-migrator cli

.github/workflows/deploy-fern-bot-dev.yml, packages/ui/fern-dashboard/src/lib/utils.ts, pnpm-lock.yaml, servers/fern-bot/package.json, servers/fern-bot/serverless.yml, servers/fern-bot/src/libs/buf.ts, servers/fern-bot/src/utils/fetchAndUnzip.ts
This fixes another `serverless.yml` duplicated name.
=> fix(fern-bot): Fix serverless.yml duplication

servers/fern-bot/src/libs/handler-wrapper.ts
=> fix(fern-bot): relax cors

servers/fern-bot/src/functions/grpc-proxy/proxyGrpc.ts
=> fix: call json.parse on lambda event

servers/fern-bot/src/functions/grpc-proxy/proxyGrpc.ts
Reverts fern-api/fern-platform#1573
=> Revert "fix: call json.parse on lambda event"

servers/fern-bot/src/libs/handler-wrapper.ts
- CORS on Options for preflight
=> fix: cors in lambda for options

servers/fern-bot/src/functions/grpc-proxy/proxyGrpc.ts
=> fix: parse json correctly

servers/fdr/src/services/algolia/AlgoliaService.ts
=> chore: revert algolia v2 cause of inf loop

packages/ui/app/src/playground/endpoint/PlaygroundEndpointContent.tsx, packages/ui/app/src/playground/endpoint/PlaygroundEndpointContentLayout.tsx, packages/ui/app/src/playground/endpoint/PlaygroundEndpointDesktopLayout.tsx, packages/ui/app/src/playground/endpoint/PlaygroundEndpointMobileLayout.tsx
- Fixes bug where unsafe type check was causing errors with deep linked playgrounds sometimes
- Bug
https://github.com/user-attachments/assets/b1ef29b5-bf1d-4993-9dff-714e86653973
=> fix: type safe endpoint safety

packages/ui/app/src/api-reference/endpoints/EndpointError.tsx
This PR fixes a small typo in error examples.
=> fix(docs): update error response

packages/ui/docs-bundle/src/server/__test__/withBasicTokenViewAllowed.test.ts, packages/ui/docs-bundle/src/server/withBasicTokenPublic.ts
=> fix: filter out childless sections

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/jwt/callback.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/ory/callback.ts, packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/webflow/callback.ts
=> chore: add error logs to auth callbacks

.github/workflows/deploy-fdr-dev.yml
=> fix: deploy fdr dev edit

.github/workflows/deploy-fdr-dev.yml, .github/workflows/publish-fdr-sdk.yml
Fixes fdr deploy script due to thrashing with sed and cat
=> fix: fdr deploy script

packages/ui/app/src/mdx/components/Audience/Audience.tsx, packages/ui/app/src/mdx/components/Audience/index.ts, packages/ui/app/src/mdx/components/index.tsx, packages/ui/fern-docs-auth/src/types.ts
Introduces the following component:
```mdx
<Audience audience="a">
> only users in group a can see this content
</Audience>
```
```mdx
<Audience audience={["a", "b"]}>
> only users in group a OR b can see this content
</Audience>
```
```mdx
<Audience not audience="a">
> users in group a will NOT be able to see this content
</Audience>
```
=> feat: audience mdx component

servers/fdr/src/services/docs-cache/DocsDefinitionCache.ts
- Add debug statement for fdr redis cache
- OOM errors
TBD
=> debug: add debug statement for fdr deploy

.github/workflows/deploy-docs-bundle-preview.yml
https://github.com/hashicorp/nextjs-bundle-analysis/blob/main/template.yml#L66-L79
=> fix: nextjs bundle anaysis

fern/apis/fdr/generators.yml, packages/template-resolver/package.json, packages/template-resolver/src/ResolutionUtilities.ts, packages/template-resolver/src/SnippetTemplateResolver.ts, packages/template-resolver/src/UnionResolver.ts, packages/template-resolver/src/__test__/cohere.ts, packages/template-resolver/src/__test__/octo.ts, packages/template-resolver/src/__test__/union.ts, packages/template-resolver/src/__test__/unit-tests/assets/imdbApiDefinition.ts, packages/template-resolver/src/__test__/unit-tests/octo.test.ts, packages/template-resolver/src/formatSnippet.ts, packages/ui/app/src/playground/code-snippets/resolver.ts, pnpm-lock.yaml
Need to publish the template resolver as a CJS package
=> chore: use fdr cjs sdk for tempalte resolver

.github/workflows/deploy-fdr-prod.yml, .github/workflows/diff-fdr-dev.yml, servers/fdr/src/services/algolia/AlgoliaService.ts
- Re-enables FDR feature flag to debug discriminated union visitation
- infinite or deep recursion
- engineering notifs
=> fix: turned feature flag back on

.github/workflows/deploy-fdr-dev.yml, .github/workflows/deploy-fdr-prod.yml, .github/workflows/diff-fdr-dev.yml
- Turns off algolia for fern, which is matching everything
- Blocked deployment
=> turn off algolia for fern, which is matching everything

servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts, servers/fdr/src/db/docs/DocsV2Dao.ts
Specify which domains are not owned by the current org. 
Makes it easier to understand why the generation has failed. 
N/A
=> fix(fdr): specify which domains are not owned by the org

packages/ui/app/src/atoms/auth.ts, packages/ui/app/src/mdx/components/if/If.test.tsx, packages/ui/app/src/mdx/components/if/If.tsx
Fixing the If component logic, and adding unit tests to verify each combination of `If roles`, `If not roles` and `If loggedIn` and `If not loggedIn`
=> fix: if component with tests

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/sso/callback.ts, packages/ui/docs-bundle/src/server/withMiddlewareAuth.ts, packages/ui/docs-bundle/src/server/xfernhost/edge.ts
Fixes how authkit callback redirection is handled
=> fix: app-staging is handled

servers/fdr/src/db/sdk/SdkDao.ts
Make sure that when we filter to latest SDK, we don't include "undefined".
Snippets are going missing. 
WIll be tested on dev + existing tests pass.
=> fix(fdr): filter to latest SDK row and add logging

servers/fdr/src/db/sdk/SdkDao.ts
PIck an SDK ID that has snippets.  
There are chances of having SDK IDs that do not have associated snippets, causing snippets to disappear. 
Will test on dev.
=> fix: return sdk id that always has snippets

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/sso/callback.ts, packages/ui/docs-bundle/src/server/auth/getAuthState.ts, packages/ui/docs-bundle/src/server/auth/workos.ts, packages/ui/fern-docs-auth/src/types.ts
This lets us redirect users directly to their IDP instead of authkit.
=> fix: set connection url directly in the edge config

servers/fdr/src/db/docs/DocsV2Dao.ts
Prevents us from storing all docs for all URLs in the same transaction to reduce transaction timeouts. Even if a single step fails for this, its okay and there are no harmful effects. 
Reducing db failures after exceeding storage timeouts. 
Will be tested by ETE tests.
=> fix(fdr): split docs storage across transactions

packages/commons/react/common-components/package.json, packages/commons/react/fonts/package.json, packages/commons/react/react-commons/package.json, packages/ui/app/package.json, packages/ui/components/package.json, packages/ui/fern-dashboard/package.json, pnpm-lock.yaml
Upgrades all of vitest to 2.x. 
Soc ii
Existing CI
=> chore: upgrade vitest everywhere

package.json, pnpm-lock.yaml
Pins webpack to `5.94.0`
Soc II
N/A
=> chore: pin webpack to `5.94.0`

packages/fdr-sdk/src/converters/index.ts, packages/fdr-sdk/src/converters/read/convertDocsDefinitionToRead.ts, pnpm-lock.yaml, servers/fdr/package.json, servers/fdr/src/controllers/docs/v1/getDocsReadService.ts, servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts, servers/fdr/src/services/algolia/AlgoliaSearchRecordGeneratorV2.ts, servers/fdr/src/util/getFilesV2.ts, servers/fdr/tsconfig.json
Reverts fern-api/fern-platform#1774
=> Revert "Revert "chore: plumb new navigation record generation""

servers/fdr/src/controllers/docs/v1/getDocsReadService.ts
* Fixes Search Info return endpoint for docs
* Search UI broken for new navigation structure
* To be tested
=> fix: update read shape to return correct search info

servers/fdr/src/services/algolia-index-segment-manager/AlgoliaIndexSegmentManagerService.ts, servers/fdr/src/services/algolia/AlgoliaService.ts, servers/fdr/src/services/algolia/types.ts
* fixes index segment generation for search records in new navigation structure
* search results not generating properly
* to be tested
=> fix: index segment generation for search records

.github/workflows/deploy-fdr-dev.yml
Trigger FDR Dev deploy on search related changes
=> trigger deploy

.github/workflows/deploy-fdr-dev.yml, .github/workflows/deploy-fdr-prod.yml, servers/fdr/.env.dev, servers/fdr/.env.prod
* Bumps pool timeout for connections, when acquiring a connection for Prisma
https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool
=> fix: bump pool timeout on acquiring connection

packages/ui/docs-bundle/src/pages/api/fern-docs/org/org-for-url.ts
UI bundle dev deploys are failing bc vercel build fails. 
This PR fixes Vercel build. 
CI is green.
=> fix deploy ci job

packages/ui/docs-bundle/src/pages/api/fern-docs/llms.txt.ts
Similar to landing page, overview pages should be appended to the top of `llms.txt` and its children are enumerated below.
=> fix: llms.txt should show the overview page

packages/ui/app/src/api-reference/types/discriminated-union/DiscriminatedUnionVariant.tsx
Fixes FER-3680
Anchors now appear on all union variants, with the same behavior as properties.
Adding anchors to union variants to support all nested links.
Tested locally to ensure anchors were appearing and produce the same behavior as properties.
=> fix(docs): Add anchors to union variants

packages/ui/fern-docs-search-ui/src/components/desktop/desktop.scss, packages/ui/fern-docs-search-ui/src/components/shared/command-hits.tsx
re-enable right-click and option+click on search results!
=> fix: make command hits anchor links

packages/ui/docs-bundle/src/pages/api/fern-docs/proxy/file.ts
=> fix(playground): handle returning audio mpeg data

packages/ui/app/src/api-reference/examples/AudioExample.tsx
This PR updates the latest audio example. 
Update the example in the docs repo. 
Yes
=> fix: update audio example

packages/fern-docs/search-server/src/algolia/index.ts, packages/fern-docs/search-ui/src/app/(demo)/app-sidebar.tsx, packages/fern-docs/search-ui/src/app/(demo)/search-demo.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop-command.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop-search-dialog.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop.scss, packages/fern-docs/ui/src/search/SearchV2.tsx
https://github.com/user-attachments/assets/e100923a-8dab-4cee-801d-783f4512363c
=> ux: add transition on search

packages/fern-docs/components/.storybook/variables.css, packages/fern-docs/components/src/FernButtonV2.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx, packages/fern-docs/tailwind.config.js, packages/fern-docs/ui/.storybook/variables.css, packages/fern-docs/ui/src/search/SearchV2.tsx, packages/fern-docs/ui/src/themes/stylesheet/getColorVariables.ts
=> fix: update padding and fix positioning

packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx, packages/fern-docs/search-ui/src/components/desktop/desktop-command.tsx, packages/fern-docs/ui/src/search/SearchV2.tsx
`/` inside of input/textarea should not open the commandbar; also fix missing input field inside commandbar
=> fix: search entrypoint

packages/fern-docs/ui/src/feedback/FeedbackForm.tsx
This updates the logic for the feedback form to ensure the correct responses are displayed.
=> fix(docs): fix feedback form logic

packages/fern-docs/bundle/package.json, packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts, pnpm-lock.yaml
Seeing weird behavior with AI chat on prod
=> Rolling back Bedrock migration

packages/parsers/package.json, packages/parsers/src/openrpc/BaseOpenApiV3_1Converter.node.ts, packages/parsers/src/openrpc/index.ts, pnpm-lock.yaml
This PR introduces a base node for the OpenRPC converter. 
N/A
=> chore(openrpc): introduce base openrpc node

packages/parsers/package.json, packages/parsers/src/index.ts, packages/parsers/src/openrpc/BaseOpenrpcConverter.node.ts, packages/parsers/src/openrpc/OpenrpcContext.ts, packages/parsers/src/openrpc/__test__/createMockContext.util.ts
Bumps the parser version so we can publish a new package version
- Publishing openrpc parser
- Simplifying openrpc context name + removing abstract nature 
N/A
=> chore(openrpc): bump package and setup publishing

.github/workflows/publish-parsers-package.yml, packages/parsers/package.json
This PR sets up a github action to publish the parsers package. 
Want a workflow to setup auto publishing instead of running this locally. 
N/A will test on merge.
=> chore(parsers): setup publishing ci task

.github/workflows/publish-parsers-package.yml, packages/parsers/package.json
This PR fixes the github workflow for publishing the parsers package. 
Automatically setup publishing of the parsers package. 
Manually tested locally
=> chore(parsers): fix github workflow

.github/workflows/publish-parsers-package.yml, packages/parsers/package.json
Build npmrc before calling publish. 
Publish failing due to auth issue. 
N/A
=> fix(parsers): instantiate npmrc before calling pnpm publish

packages/parsers/package.json, packages/parsers/src/openrpc/1.x/MethodConverter.node.ts, packages/parsers/src/openrpc/1.x/OpenrpcDocumentConverter.node.ts, packages/parsers/src/openrpc/__test__/OpenrpcConverter.test.ts, packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json, packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json, packages/parsers/src/openrpc/__test__/__snapshots__/solana.json, packages/parsers/src/openrpc/__test__/fixtures/solana/openrpc.json
This PR updates the display name for OpenRPC endpoints and adds support for environments. 
Get generated API Reference to feel native
Snapshots
=> feat(openrpc): support environments

packages/parsers/package.json, packages/parsers/src/examples/generateExampleForJsonSchema.ts, packages/parsers/src/openrpc/1.x/MethodConverter.node.ts, packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json, packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json, packages/parsers/src/openrpc/__test__/__snapshots__/solana.json
For OpenRPC we autogenerate examples when none are present. 
Don't want to manually write examples for OpenRPC. 
**Note** this is a poor man's example generator and not ready for broad adoption. 
Snapshots
=> feat(openrpc): introduce json schema examle generator

packages/fern-docs/ui/src/feature-flags/FeatureFlagProvider.tsx
fixes issue with ssr on launchdarkly-enabled docs sites
=> fix: turn ssr=true on for FeatureFlagProvider

packages/fern-docs/bundle/package.json, packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts, pnpm-lock.yaml, turbo.json
Instrument LLM calls to braintrust. 
Understanding more about our AI chat. 
N/A
=> chore(docs): start instrumenting braintrust

servers/fdr/src/services/s3/S3Service.ts
Reverts fern-api/fern-platform#2042
=> Revert "fix(fdr): public s3 file uploads go through cloudfront"

servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts, servers/fdr/src/services/s3/S3Service.ts
Store the right format in S3. 
Speed up docs!
Type safety
=> fix(fdr): store the right docs in s3

packages/fern-docs/bundle/src/server/DocsLoader.ts, packages/fern-docs/bundle/src/server/__test__/loadDocsDefinitionFromS3.test.ts, packages/fern-docs/bundle/src/server/analytics/posthog.ts, packages/fern-docs/bundle/src/server/loadDocsDefinitionFromS3.ts
Refactor loadDocsDefinitionFromS3
We are in a code freeze till this works!!
Added a unit test
=> fix(docs): unit test the load with url

packages/fern-docs/bundle/package.json, packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts, packages/fern-docs/bundle/src/server/loadDocsDefinitionFromS3.ts, pnpm-lock.yaml
=> Reverting braintrust implementation, will spin off a new branch

packages/parsers/package.json, packages/parsers/src/openrpc/1.x/MethodConverter.node.ts, packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json, packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json, packages/parsers/src/openrpc/__test__/__snapshots__/solana.json
OpenRPC schema conversion handles required false. 
Snapshots.
=> fix(openrpc): handle require false

packages/parsers/package.json, packages/parsers/src/openrpc/1.x/MethodConverter.node.ts, packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json, packages/parsers/src/openrpc/__test__/__snapshots__/solana.json
JSON RPC metadata gets automatically added to the docs. 
Snapshot tests.
=> fix(openrpc): dont add jsonrpc metadata to examples

packages/fern-docs/auth/package.json, packages/fern-docs/bundle/package.json, packages/fern-docs/edge-config/package.json, packages/fern-docs/search-server/package.json, packages/fern-docs/search-ui/package.json, packages/fern-docs/ui/package.json, pnpm-lock.yaml, servers/fern-bot/package.json
=> Upgrading zod

packages/fern-docs/seo/src/with-seo.ts
This PR updates SEO descriptions for the API Reference to convert Markdown to pure text. 
Before:
After:
=> chore: update api seo description

packages/fern-docs/ui/package.json, packages/fern-docs/ui/src/mdx/components/index.tsx, packages/fern-docs/ui/src/mdx/components/json/JSON.tsx, packages/fern-docs/ui/src/mdx/components/json/index.ts, pnpm-lock.yaml
This PR introduces a component for expandable and collapsible json. 
Customer Demand
Local preview
=> feat(docs): introduce JSON component for expandable/collapsible json

packages/fern-docs/ui/src/mdx/components/card/index.scss, packages/fern-docs/ui/src/mdx/components/json/JSON.tsx, packages/fern-docs/ui/src/mdx/components/json/index.scss
Fixes FER-4394
https://linear.app/buildwithfern/issue/FER-4394/json-viewer-nitsrequest
AssemblyAI requested JSON viewer
Manually
=> fix: styling, copy button, arary & key indicators

packages/fern-docs/ui/src/hooks/useInterceptNextDataHref.ts
Reverts fern-api/fern-platform#2119
=> Revert "fix: attempt to fix routing"

packages/fern-docs/ui/src/themes/default/DefaultDocs.tsx, packages/fern-docs/ui/src/themes/default/index.scss
Fixes the footer behavior on mobile menu open:
https://github.com/user-attachments/assets/cf542784-0189-4f70-a097-925fb195249d
=> chore: footer docs fix

packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts
Reduce tokens for each query. 
Reduce rate limiting w/o reducing quality that much
N/A
=> chore: ai search filters to top 5 documents to reduce tokens

packages/fern-docs/mdx/src/__test__/toc.test.ts, packages/fern-docs/mdx/src/mdx-utils/extract-literal.ts, packages/fern-docs/mdx/src/toc.ts
Issue: missed drilling a prop in the makeToc file. Fixed with a test
=> fix: add feature flagged toc tests

packages/fern-docs/mdx/src/toc.ts, packages/fern-docs/ui/src/mdx/components/accordion/AccordionGroup.tsx, packages/fern-docs/ui/src/mdx/plugins/rehypeFernComponents.ts
Follow-ups:
- fix scroll jacking behavior
- clear the anchor link when an accordion is closed
https://github.com/user-attachments/assets/c094215d-e745-4932-af0b-47aa108e58ef
=> fix: new accordion behavior

packages/fern-docs/bundle/src/server/auth/getAuthState.ts
=> feat: remove upstash call in the proxy

packages/fern-docs/cache/src/MarkdownKVCache.ts
Reverts fern-api/fern-platform#2214
=> Revert "fix: set TTL on kv entries"

servers/fdr/src/controllers/api/getRegisterApiService.ts, servers/fdr/src/db/snippets/SnippetsDao.ts
Builds upon the changes in https://github.com/fern-api/fern-platform/pull/2218
=> fix(csharp): Convert C# snippets from DB

packages/fern-docs/edge-config/src/getEdgeFlags.ts, packages/fern-docs/ui/src/api-reference/ApiEndpointPage.tsx, packages/fern-docs/ui/src/api-reference/ApiReferencePage.tsx, packages/fern-docs/ui/src/atoms/playground.ts, packages/fern-docs/ui/src/playground/PlaygroundFloatingButton.scss, packages/fern-docs/ui/src/playground/PlaygroundFloatingButton.tsx, packages/fern-docs/utils/src/flags.ts
This PR adds the floating action button for the API Explorer
=> feat: try it FAB

packages/fern-docs/bundle/src/components/api-reference/endpoints/EndpointContentCodeSnippets.tsx, packages/fern-docs/bundle/src/components/api-reference/examples/TitledExample.tsx, packages/fern-docs/bundle/src/components/api-reference/websockets/WebSocket.tsx, packages/fern-docs/bundle/src/components/playground/PlaygroundButton.tsx, packages/fern-docs/bundle/src/components/playground/PlaygroundButtonTray.tsx, packages/fern-docs/bundle/src/components/playground/PlaygroundFloatingButton.scss, packages/fern-docs/bundle/src/components/playground/PlaygroundFloatingButton.tsx, packages/fern-docs/bundle/src/components/playground/index.scss, packages/fern-docs/bundle/src/mdx/components/snippets/EndpointRequestSnippet.tsx
=> chore: copy try it button

packages/fern-docs/ui/src/atoms/playground.ts
Disables playground examples for spscommerce
N/A
=> chore: disable playground examples for spscommerce

packages/fern-docs/ui/src/playground/endpoint/PlaygroundResponseCard.tsx
Updates `PlaygroundResponseCard` to handle json responses. 
Failing to show `application/+json` responses on a file download endpoint. 
N/A
=> fix(playground): json responses are all shown in the playground

packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.test.ts, packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.ts
=> chore: update meta parsing

packages/fern-docs/bundle/src/mdx/components/card/Card.tsx, packages/fern-docs/bundle/src/mdx/plugins/rehype-cards.ts
ensure iconSize is a number
before: 
after:
=> fix: check for nan

packages/fern-docs/search-server/src/utils/system-prompt.ts
=> Update AI chat system prompt to avoid edge-cases

.github/actions/install/action.yml, package.json, packages/fern-docs/bundle/src/components/css/components.scss, packages/fern-docs/bundle/src/components/playground/endpoint/PlaygroundEndpoint.scss, packages/fern-docs/bundle/src/components/sidebar/index.scss, packages/fern-docs/utils/.depcheckrc.json
Use pnpm version `9.15.5` on app branch
=> chore: use pnpm 9.15.5 on app

packages/fern-docs/bundle/src/mdx/bundler/serialize.ts
Tries to reduce file operations and move to in-memory to make mdx serialization possible. 
MDX serialization failures being encountered on prod
N/A
=> fix: finetune esbuild options

packages/fern-docs/bundle/src/mdx/bundler/serialize.ts, packages/fern-docs/bundle/src/server/mdx-serializer.ts
- Special case empty string
- Revert esbuild options
- Slack notifiy with broken content
=> chore: special case content and revert options

packages/fern-docs/bundle/src/middleware.ts, packages/fern-docs/utils/src/constants.ts
This PR sets `x-forwarded-host` in the middleware
=> chore(docs): set x-forwarded-host for server actions

packages/fern-docs/bundle/src/components/themes/default/DefaultDocs.tsx
makes it easier to select the footer
=> chore: update footer id

packages/fern-docs/bundle/src/components/PageHeader.tsx, packages/fern-docs/bundle/src/components/api-reference/endpoints/EndpointContent.tsx, packages/fern-docs/bundle/src/components/api-reference/webhooks/WebhookContent.tsx, packages/fern-docs/bundle/src/components/api-reference/websockets/WebSocket.tsx, packages/fern-docs/bundle/src/components/changelog/ChangelogEntryPage.tsx, packages/fern-docs/bundle/src/components/changelog/ChangelogPage.tsx, packages/fern-docs/bundle/src/components/layouts/LayoutEvaluator.tsx, packages/fern-docs/bundle/src/components/layouts/LayoutEvaluatorContent.tsx, packages/fern-docs/bundle/src/components/shared-page.tsx, packages/fern-docs/bundle/src/mdx/bundler/__snapshots__/cards.js, packages/fern-docs/bundle/src/mdx/bundler/__snapshots__/import-constants.js, packages/fern-docs/bundle/src/mdx/bundler/serialize.test.ts, packages/fern-docs/bundle/src/mdx/bundler/serialize.ts, packages/fern-docs/bundle/src/mdx/components/server-component.tsx, packages/fern-docs/bundle/src/server/docs-loader.ts, packages/fern-docs/bundle/src/server/mdx-serializer.ts, packages/fern-docs/bundle/src/server/slack.ts
=> chore: add logging and tests for serialize mdx with imports

packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts, packages/fern-docs/syntax-highlighter/src/CodeBlockWithClipboardButton.tsx, packages/fern-docs/ui/src/mdx/components/code/CodeBlock.tsx, packages/fern-docs/ui/src/mdx/components/code/CodeGroup.tsx, packages/fern-docs/ui/src/mdx/components/code/Template.tsx, packages/fern-docs/ui/src/mdx/components/index.tsx
Backports changes made in https://github.com/fern-api/fern-platform/pull/2310
=> backport: templates component

packages/fern-docs/bundle/src/mdx/components/download/Download.tsx, packages/fern-docs/bundle/src/mdx/components/download/index.ts, packages/fern-docs/bundle/src/mdx/components/index.tsx
=> chore: reimplement download button

packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.test.ts, packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.ts
This PR will unblock Comet from moving to the app router.
=> chore: leave metadata

packages/fern-docs/bundle/src/mdx/plugins/rehype-accordions.ts
=> chore: support expandable

packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.ts
restores mermaid diagram parsing
=> fix: save the mermaids!

packages/fern-docs/bundle/src/components/playground/PlaygroundButton.tsx, packages/fern-docs/bundle/src/components/playground/PlaygroundButtonTray.tsx, packages/fern-docs/components/src/FernButtonV2.tsx
makes the explorer button its own variant
=> chore: explorer button variant 

packages/fern-docs/bundle/src/components/table-of-contents/TableOfContents.tsx, packages/fern-docs/mdx/package.json, packages/fern-docs/mdx/src/__test__/toc.test.ts, packages/fern-docs/mdx/src/toc.ts, pnpm-lock.yaml
mirrors
- https://github.com/fern-api/fern-platform/pull/2192
- https://github.com/fern-api/fern-platform/pull/2196
=> chore: add feature flags to the toc

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/search/v2/chat/route.ts, packages/fern-docs/search-server/src/turbopuffer/query.ts, packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx, pnpm-lock.yaml
=> fix: Turbopuffer now respects search UI filters (e.g. version) [app branch]

packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.test.ts, packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.ts
=> chore: update meta parsing for wordwrap

packages/fern-docs/components/src/FernDatetimeInput.tsx
resolve component issue for brightmove
=> fix: add fallback for date format

packages/fern-docs/bundle/src/components/FernAnchor.scss, packages/fern-docs/bundle/src/components/bottom-nav-client.tsx, packages/fern-docs/bundle/src/components/header/Announcement.tsx, packages/fern-docs/bundle/src/components/themes/cohere/CohereDocs.tsx, packages/fern-docs/bundle/src/mdx/components/code/CodeBlock.tsx, packages/fern-docs/bundle/src/mdx/components/html-table/index.scss, packages/fern-docs/components/src/index.css, packages/fern-docs/components/src/syntax-highlighter/CodeBlockWithClipboardButton.tsx
https://linear.app/buildwithfern/issue/FER-4715/unrevert-css-fixes-for-cohere
=> chore: unrevert cohere css updates

packages/commons/fdr-utils/src/types.ts, packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/@versionSelect/[slug]/page.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/layout.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/static/@versionSelect/[slug]/page.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/static/layout.tsx, packages/fern-docs/bundle/src/components/header/VersionDropdown.tsx, packages/fern-docs/bundle/src/components/header/VersionDropdownClient.tsx, packages/fern-docs/bundle/src/components/shared-layout.tsx, packages/fern-docs/bundle/src/server/withVersionSwitcherInfo.ts
adds version matching for app router
=> chore: version matching

packages/fern-docs/mdx/src/plugins/__test__/__snapshots__/rehype-expression-to-md.test.ts.snap, packages/fern-docs/mdx/src/plugins/__test__/rehype-expression-to-md.test.ts
finishes mirror of https://github.com/fern-api/fern-platform/pull/2139
=> backport: add test for rehype-expression-to-md

packages/fern-docs/bundle/src/components/shared-page.tsx, packages/fern-docs/bundle/src/mdx/bundler/serialize.ts, packages/fern-docs/bundle/src/mdx/plugins/rehype-links.test.ts, packages/fern-docs/bundle/src/mdx/plugins/rehype-links.ts, packages/fern-docs/bundle/src/server/mdx-serializer.ts
mirrors https://github.com/fern-api/fern-platform/pull/2147/files
=> backport: resolve hrefs in markdown

packages/fern-docs/bundle/package.json, packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/llms-full.txt/route.ts, packages/fern-docs/bundle/src/mdx/components/index.tsx, packages/fern-docs/bundle/src/mdx/components/json/JSON.tsx, packages/fern-docs/bundle/src/mdx/components/json/index.scss, packages/fern-docs/bundle/src/mdx/components/json/index.ts, pnpm-lock.yaml
=> backport: add json block + styling

packages/fern-docs/bundle/src/mdx/components/json/JSON.tsx
=> fix: json line wrap

servers/fdr/src/services/revalidator/RevalidatorService.ts
Cherry-picks https://github.com/fern-api/fern-platform/commit/58ee815cdefd52cf7498c6fae412fdc2536396d1 from main
=> Update RevalidatorService.ts to hit the revalidation service without the fern client

packages/fern-docs/search-server/src/utils/system-prompt.ts
Fixes FER-
<version></version> -> ## version (markdown change, helps legibility)
Accidentally reverted a previous fix
=> fix: Hotfix system-prompt

packages/fern-docs/bundle/src/components/api-reference/ApiEndpointPage.tsx
this pr fixes the streaming toggle for the API reference
=> fix: stream toggle

packages/fern-docs/bundle/src/components/sidebar/SidebarLink.tsx
this PR enforces line wrapping within sidebar links
=> chore: update link wrap

pnpm-lock.yaml, servers/fern-bot/package.json, servers/fern-bot/src/libs/github/octokitHooks.ts
Fixes FER-
Upgraded octokit to resolve vulnerabilities in underlying dependencies
SOC II
=> chore: update octokit for dependabot alerts

packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/@logo/[slug]/page.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/layout.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/static/@logo/[slug]/page.tsx, packages/fern-docs/bundle/src/app/[host]/[domain]/static/layout.tsx, packages/fern-docs/bundle/src/components/shared-layout.tsx
this PR fixes functionality to resore the ability to set the logo of a website from the frontmatter of a given page.
=> fix: frontmatter logo config

packages/fern-docs/search-ui/package.json, packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx, pnpm-lock.yaml
Fixes FER-
Old AI package version breaks with Bedrock
Blocking cohere-ai
Local
=> fix: bump AI/react version to fix AI chat bug

packages/fern-docs/bundle/src/components/playground/utils/auth-headers.test.ts, packages/fern-docs/bundle/src/components/playground/utils/auth-headers.ts
this PR fixes the encoding of basic authentication
=> chore: fix auth encoding

.github/workflows/deploy-fern-docs.yml
Since `Production-Assets` deployed totally fine, this uncomments the workflows. 
Setup docs to deploy via github action. 
See description.
=> chore: uncomment releasing workflow

packages/fern-docs/bundle/src/mdx/components/tabs/Tabs.tsx
Fixes FER-
- Added overflow scroll on tabs
- Requested by customer
- Manually
=> fix: added overflow on tabs

fern/apis/fdr/definition/api/v1/register/type.yml, packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/resources/type/types/UndiscriminatedUnionVariant.ts, packages/fdr-sdk/src/converters/db/convertAPIDefinitionToDb.ts, packages/fern-docs/bundle/src/server/mdx-serializer.ts, servers/fdr/src/api/generated/api/resources/api/resources/v1/resources/register/resources/type/types/UndiscriminatedUnionVariant.d.ts
Fixes FER-
- add displayName to UndiscriminatedUnionVariant in `v1/register`
- add `displayName` to undiscriminatedUnion type during initial store
- unit tests
=> feat: add displayName to UndiscriminatedUnionVariant in `v1/register`
