packages/ui/app/src/docs/BgImageGradient.tsx

Change background gradient color

---

.github/workflows/postman.yml
fern/apis/fdr/generators.yml
fern/fern.config.json

This adds a simple workflow for creating a Postman collection using the `fern-api/postman` generator. With this, we can update the FDR postman collection manually using the `workflow_dispatch`, and it can be wired up via automation with the `workflow_call` later (if ever).

feat(ci): Add postman generator workflow

---

packages/ui/app/src/api-reference/types/type-shorthand/TypeShorthand.tsx

- remove quotes around boolean literals
- change "union" to "object" for discriminated unions, since the union is implied by the variants
- change "union" to `string or number or object` for undiscriminated unions
- for enums, if there are only one or two options, treat them like literals

fix: type shorthand improvements

---

packages/fdr-sdk/src/navigation/ApiDefinitionPruner.ts
packages/ui/app/src/api-reference/endpoints/EndpointContent.tsx
packages/ui/app/src/api-reference/endpoints/EndpointContentHeader.tsx
packages/ui/app/src/util/convertNavigatableToResolvedPath.ts

Fixes bug introduced from https://github.com/fern-api/fern-platform/pull/1379 where the stream and nonstream toggle disappeared on paginated api references

fix: stream-nonstream toggle appears on paginated docs

---

packages/ui/app/src/api-reference/endpoints/Endpoint.tsx
packages/ui/app/src/atoms/apis.ts
packages/ui/app/src/atoms/docs.ts
packages/ui/app/src/atoms/navigation.ts
packages/ui/app/src/atoms/sidebar.ts
packages/ui/app/src/atoms/store.ts
packages/ui/app/src/atoms/types.ts
packages/ui/app/src/changelog/ChangelogEntryPage.tsx
packages/ui/app/src/changelog/ChangelogPage.tsx
packages/ui/app/src/components/ApiReferenceButton.tsx
packages/ui/app/src/components/BottomNavigationButton.tsx
packages/ui/app/src/docs/DocsMainContent.tsx
packages/ui/app/src/docs/DocsPage.tsx
packages/ui/app/src/docs/NextApp.tsx
packages/ui/app/src/index.ts
packages/ui/app/src/mdx/components/snippets/EndpointRequestSnippet.tsx
packages/ui/app/src/mdx/components/snippets/EndpointResponseSnippet.tsx
packages/ui/app/src/resolver/DocsContent.ts
packages/ui/app/src/themes/ThemedDocs.tsx
packages/ui/app/src/themes/cohere/CohereDocs.tsx
packages/ui/app/src/themes/default/DefaultDocs.tsx
packages/ui/app/src/util/convertNavigatableToResolvedPath.ts
packages/ui/app/src/util/resolveDocsContent.ts
packages/ui/docs-bundle/src/utils/getDocsPageProps.ts
packages/ui/local-preview-bundle/src/utils/getDocsPageProps.ts

This PR fixes an issue with `useHydrateAtoms`, which actually defers rendering by 1 frame.
Effectively, the content captured in the useHydrateAtoms hook will get rendered _after_ nextjs's client side router completes navigation to another page.
- rename "resolvedPath" to "content" and `ResolvedPath` to `DocsContent` clarity
- removes the root-level jotai `<Provider>` in favor of using the DefaultStore
- pass docs content directly to the content renderer, which gets rendered at the 0th frame
https://buildwithfern.slack.com/archives/C06QKJWD4VD/p1725625436049009
This issue occurs because scroll occurs on the 0th frame, before the content has a chance to render on the 1st frame. With this change, the content renders on the 0th frame which coincides with when the scroll position is computed.

fix: initialize atoms at the root level

---

packages/ui/app/src/sidebar/index.scss

Fixes a CSS bug caused by https://github.com/fern-api/fern-platform/pull/1410 where the nested expansion is hidden because the height is fixed by animation-fill-mode=forwards

fix: nested expansion css issue

---

packages/ui/app/src/api-reference/endpoints/EndpointResponseSection.tsx

This PR adds punctuation to consistently format the description of the response payload. 
Testing:

fix(docs): format response descriptions

---

pnpm-lock.yaml
servers/fern-bot/serverless.yml
servers/fern-bot/src/functions/generator-updates/shared/updateGeneratorInternal.ts
servers/fern-bot/src/libs/fern.ts
servers/fern-bot/src/libs/slack/SlackService.ts

Fixes FER-3203
This PR:
- updates the npm prefix to ensure we're writing to a writable dir in lambdas (previously only `npx` was overridden, this adds the additional config which fixes `npm install` which is needed by `fern upgrade`)
- reinstalls the fern cli to have it at a known location given the override above
- moves the fern org check for generator upgrades only, not CLI upgrades, this allows us to upgrade the fleet to a CLI version that is compatible with generator upgrades before we roll that out more widely

fix(fern-bot): allow npm install to work on lambdas

---

packages/ui/app/src/atoms/sidebar.ts
packages/ui/app/src/sidebar/Sidebar.tsx

https://github.com/fern-api/fern-platform/pull/1304 change is not necessarily true. we do want to sometimes render dismissible sidebars in certain cases. for example: when the markdown is `page` or `custom`.
This fixes the problem where sometimes hidden pages do not render a sidebar at all, which causes users to be unable to navigate to other pages on the same tab.

fix: hidden pages should not disable the sidebar

---

packages/ui/app/src/themes/cohere/index.scss

Before:
AFter:
- perfectly centered content

fix: resolve padding issues on cohere's hidden pages

---

packages/ui/app/src/syntax-highlighting/FernSyntaxHighlighterTokens.tsx

Fixes [FER-3230](https://linear.app/buildwithfern/issue/FER-3230/syntax-highlighting-is-not-enabled-on-page-load)

fix: syntax highlighter memoization

---

packages/ui/app/src/api-reference/endpoints/EndpointUrl.tsx
packages/ui/app/src/util/endpoint.ts

Before this PR: trailing slash is omitted in the EndpointUrl renderer
After this PR: all original slashes are preserved

fix: never strip the trailing slash in the EndpointUrl

---

packages/ui/app/src/changelog/ChangelogPage.tsx
packages/ui/app/src/mdx/Markdown.tsx

This addresses an SEO problem where multiple \<h1\> are appearing on the same page

fix: changelog entry titles are rendered with <h2> rather than <h1>

---

packages/fdr-sdk/src/navigation/utils/createBreadcrumbs.ts
packages/ui/app/src/components/FernBreadcrumbs.tsx

fix: remove breadcrumbs with empty title

---

packages/ui/app/src/playground/PlaygroundAuthorizationForm.tsx

- ensures no weird ouath overflow if long OAuth flow
- Chariot's OAuth drawer looked strange: 
- Now it doesn't:

fix: increase to max height to prevent weird overflow

---

packages/ui/app/package.json
packages/ui/app/src/analytics/posthog.ts
packages/ui/docs-bundle/next.config.js
packages/ui/docs-bundle/package.json
packages/ui/docs-bundle/sentry.client.config.ts
packages/ui/docs-bundle/sentry.edge.config.ts
packages/ui/docs-bundle/sentry.server.config.ts
packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/utils/rewritePosthog.ts
pnpm-lock.yaml

sentry tunneling is configured to send cross-origin requests
- https://github.com/fern-api/fern-platform/pull/1453 upgraded sentry to 8.x which caused tunneling to stop working.
- also, removes posthog tunneling for the customer (saves our vercel bill, and offloads CORS responsibility to the customer)

fix: allow cross-origin requests to sentry tunnel

---

packages/ui/app/src/changelog/ChangelogPage.tsx
packages/ui/app/src/util/__test__/parseMarkdownToAnchorId.test.ts
packages/ui/app/src/util/resolveDocsContent.ts

humanloop released a newsletter with an anchor link to the changelog page. since we've implemented pagination, that link will be broken if it's on a page > 1. this PR attempts to solve that challenge by opening the correct page of the changelog immediately

fix: implement anchor logic in long scrolling changelog

---

servers/fern-bot/src/__test__/basic-ete.test.ts
servers/fern-bot/src/functions/generator-updates/shared/updateGeneratorInternal.ts

If a version upgrade is not found within your current major version, we then try to do an upgrade with major and see if there are any upgrades to then create a slack alert for ourselves
The problem was that we'd then leave the repo state dirty and when you check out the next branch, the major version change would persist to the next PR
This now resets the branch after the major version has been derived

fix(fern-bot): reset any changes from trying to derive a major version upgrade

---

packages/ui/app/src/components/MaybeEnvironmentDropdown.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointPath.tsx

Fixes FER-3184
- Add missing trailing path to api playground url
- monite was broken, see linear ticket

add trailing path to parsed url in playground

---

packages/ui/app/src/changelog/ChangelogContentLayout.tsx
packages/ui/app/src/changelog/ChangelogPage.tsx
packages/ui/app/src/changelog/index.scss
packages/ui/app/src/css/globals.scss
packages/ui/app/src/sidebar/nodes/SidebarChangelogNode.tsx

Cohere's stylesheet is broken due to use of tailwind classes that get overridden by cohere's own.
----
After this PR:

fix: migrate changelog classnames to stylesheet

---

packages/ui/app/src/components/BottomNavigationButtons.tsx

fix: bottom navigation button should be full width

---

.github/workflows/deploy-docs-bundle-prod.yml
clis/vercel-scripts/src/cli.ts
clis/vercel-scripts/src/utils/global-config.ts
clis/vercel-scripts/src/utils/revalidator.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v4.ts

- Fixes revalidate-all/v4 pagination (offset * limit)
- Allows you to run `pnpm vercel-scripts` without an explicit token parameter
- Fixes production deployment action script
- Removes `req.headers.host` from revalidation script

fix: revalidator, global-config

---

packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v4.ts
packages/ui/docs-bundle/src/pages/static/[host]/[[...slug]].tsx
packages/ui/docs-bundle/src/server/DocsCache.ts
pnpm-lock.yaml

implements a KV cache which
- every time a SSG page is successfully loaded, add to the cache
- every time a SSG page is a 404 or 3xx, remove from the cache
during the revalidate-all process, we will revalidate all previously visited pages that was removed from the sitemap, thereby removing from Next.js's data cache the previously SSG'd responses that are no longer applicable.

fix: when revalidating, revalidate all previously visited pages

---

servers/fdr/src/__test__/local/services/git.test.ts
servers/fdr/src/db/git/GitDao.ts

This adds a dummy test in part just to rerelease FDR but also sanity check that the git controller is plumbed through
This also has a prisma change for correctness

chore(fdr): add local test for git to confirm things are hooked up

---

packages/ui/app/src/components/table-of-contents/useTableOfContentsObserver.ts

Fixes https://buildwithfern.sentry.io/issues/5869128804/?environment=prod&project=4507148139495424&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=7&utc=true

fix: query selectors should never have empty id

---

packages/ui/app/src/playground/code-snippets/resolver.ts

Fixes FER-3298
- Adds javascript check for snippet resolver for back compat
- Workato playground was unable to open on machines where the snippet lang atom is set to "javascript"
https://github.com/user-attachments/assets/20733ab3-17d8-4b4f-a2c7-374c8e089c3f

fix: add javascript check for snippet resolver for back compat

---

.github/workflows/deploy-docs-bundle-prod.yml
clis/vercel-scripts/src/cli.ts
clis/vercel-scripts/src/commands/rollback.ts

switches the order of the ete tests to run _after_ deployment succeeded, which may not pre-empt issues, but will self-resolve issues by rolling back the deployment upon failure

fix: production ete flow

---

packages/ui/fern-docs-utils/package.json
packages/ui/fern-docs-utils/src/__test__/getRedirectForPath.test.ts
packages/ui/fern-docs-utils/src/getRedirectForPath.ts
pnpm-lock.yaml

path-to-regexp 7 introduces breaking changes that make `:path*` wildcarding more difficult to write. Next.js uses 6.x.x (https://github.com/vercel/next.js/blob/b72c99d084de73d6c490bcf8b6a924042789ea68/packages/next/package.json#L278) so we'll pin to the same version, and add tests to ensure that we can adhere to the `:path*` wildcarding syntax.

fix: use path-to-regexp@6 to align with nextjs syntax

---

.eslintrc.js
packages/ui/app/src/api-reference/endpoints/EndpointContent.tsx
packages/ui/app/src/atoms/playground.ts
packages/ui/app/src/playground/PlaygroundDrawer.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpoint.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointFormButtons.tsx

Before this PR: When clicking `Clear form` in the API Playground after switching from one endpoint to another, it fails to clear form.
After this PR: fix memoization dependency and add eslint rules to prevent this from happening again

fix: clear form in api playground

---

servers/fdr/scripts/run.sh
servers/fdr/src/__test__/ete/ete.test.ts
servers/fdr/src/services/docs-cache/DocsDefinitionCache.ts

Caching respects semantic versioning
We need to stop doing expensive stuff in get static props and move it to the real backend
Will add a unit test, pending confirmation from @abvthecity that he's aligned with this approach

chore(fdr): setup semantic caching

---

packages/ui/app/src/index.ts
packages/ui/app/src/mdx/bundler.ts
packages/ui/app/src/resolver/ApiDefinitionResolver.ts
packages/ui/app/src/resolver/ApiEndpointResolver.ts
packages/ui/app/src/resolver/ApiTypeResolver.ts
packages/ui/app/src/resolver/__test__/ApiDefinitionResolver.test.ts
packages/ui/app/src/util/resolveDocsContent.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/resolve-api.ts

Extracts `serializeMdx` from the APIResolver. 
By extracting `serializeMdx` into an interface, we can optionally have other callers provide a cached implementation to improve performance.

chore(ui): refactor resolve-api to take serializeMdx as input

---

packages/ui/app/src/hooks/__test__/useHref.test.ts
packages/ui/app/src/hooks/useHref.ts
packages/ui/app/src/seo/getSeoProp.ts

gets rid of the leading slash:
bug introduced in https://github.com/fern-api/fern-platform/pull/1538

fix: canonical url leading slash

---

packages/ui/app/src/index.ts
packages/ui/app/src/resolver/ApiDefinitionResolver.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/resolve-api.ts
packages/ui/docs-bundle/src/server/DocsCache.ts
packages/ui/fern-dashboard/src/lib/utils.ts

This PR introduces a caching layer to `APIDefinitionResolver`. 
The playground is way too slow to load. 
It has not really been tested, hoping to use staging links.

fix: cache endpoint definitions in `resolve-api` route

---

packages/ui/app/src/resolver/ApiDefinitionResolver.ts
packages/ui/docs-bundle/src/server/DocsCache.ts

Because endpoint caching works, we now also cache pages and endpoint pairs. 
Try to get humanloop and workato API playground to load instantly. 
Testing on dev

feat(ui): cache endpoint pages and pairs

---

packages/commons/search-utils/src/getSlugForSearchRecord.ts
servers/fdr/src/services/algolia/AlgoliaSearchRecordGeneratorV2.ts

- Adds full slug to breadcrumbs and url slug
- Not plagued by same issue as page v2, as version information is no longer appended to the record
- manual tests
To be tested

fix: search small slug fix

---

servers/fern-bot/serverless.yml

This fixes a small typo in the `serverless.yml` and reconfigures the HTTP endpoint timeout.

fix(fern-bot): Fix state machine in serverless.yml

---

servers/fdr/src/services/revalidator/RevalidatorService.ts

default batch size for revalidate-all/v4 is 10. this PR bumps the revalidate-all loop in FDR to 100 (the max) to speed up revalidation.

fix: speed up revalidation with larger batch sizes

---

pnpm-lock.yaml
servers/fdr/package.json
servers/fdr/src/services/revalidator/RevalidatorService.ts

This PR reverts revalidate-all v4 in case too many deployments cant update their docs.

revert to use revalidate all v3

---

packages/ui/app/src/playground/endpoint/PlaygroundEndpointRequestCard.tsx

- There was an added errant parenthesis, we remove this
- Visual bug
Before:
After:

fix: remove errant parenthesis

---

packages/ui/app/src/api-reference/endpoints/EndpointContent.tsx
packages/ui/app/src/api-reference/endpoints/EndpointContentLeft.tsx
packages/ui/app/src/api-reference/endpoints/EndpointResponseSection.tsx
packages/ui/app/src/api-reference/types/type-shorthand/TypeShorthand.tsx

Fixes FER-3337
- Adds "server side events" to the response text for SSE typed example responses.
- Cohere ask

fix: added server sent events text on sse example

---

fern/apis/fdr/definition/docs/latest/frontmatter.yml
packages/fdr-sdk/src/client/generated/api/resources/docs/resources/latest/resources/frontmatter/types/Frontmatter.ts
packages/ui/app/src/seo/getSeoProp.ts
servers/fdr/src/api/generated/api/resources/docs/resources/latest/resources/frontmatter/types/Frontmatter.d.ts

Fixes FER-3342
- Adds ability to add canonical tag to frontmatter, with `canonical-url`
- SEO issues

feat: added ability to add canonical url to frontmatter

---

packages/ui/app/src/auth/OAuth2Client.ts
packages/ui/app/src/auth/getApiKeyInjectionConfig.ts
packages/ui/app/src/auth/types.ts
packages/ui/docs-bundle/package.json
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/api-key-injection.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/logout.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/ory/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/webflow/callback.ts
pnpm-lock.yaml

Integrates oauth callback using webflow.
notes:
- new api route `/api/fern-docs/oauth/webflow/callback` is created to disambiguate from the `ory` and `workos` callback urls. this is important so that webflowclient is compiled separately from ory and workos, otherwise the edge function will eventually blow up in size (and fail to compile)
- new api route `/api/fern-docs/oauth/ory/callback` is created with a permanent redirect to it from `/api/fern-docs/auth/callback`. someone needs to reach out to rightbrain to update their actual callback urls, but this should work in the interim.
what's next:
- testing the oauth callback flow. the edge config is set for https://webflow-migration.docs.buildwithfern.com
what i'm not a fan of:
- theres some weird hackery magic going on in the ory-based …

init: webflow oauth integration

---

packages/ui/app/src/auth/OAuth2Client.ts
packages/ui/app/src/auth/getApiKeyInjectionConfig.ts
packages/ui/app/src/auth/getAuthEdgeConfig.ts
packages/ui/app/src/auth/types.ts
packages/ui/app/src/playground/PlaygroundAuthorizationForm.tsx
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/api-key-injection.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/logout.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/ory/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/webflow/callback.ts

- auto-computed redirect_uri is causing problems where it should be considered static.
- redirection should always uses the x-fern-host domain not the nexturl.origin because of proxied docs.

fix: redirect_uri should be set in edge config

---

packages/ui/app/src/api-reference/ApiEndpointPage.tsx
packages/ui/app/src/api-reference/endpoints/EndpointUrl.tsx
packages/ui/app/src/atoms/environment.ts
packages/ui/app/src/components/MaybeEnvironmentDropdown.tsx
packages/ui/app/src/playground/code-snippets/useSnippet.ts
packages/ui/app/src/playground/utils/select-environment.ts

- Fixes visual and functional issues related to playground v2 migration
- Broken state
https://github.com/user-attachments/assets/683e4fef-3d50-4aeb-b3c1-bcb4d22e00f3

fix: restore functionality for dropdowns, switchers and other API_ATOM derivatives

---

packages/ui/app/src/mdx/components/callout/Callout.tsx

This PR adds the `icon` attribute to the Callout options so that custom icons can be used in the various Callout-styled components.  
The example below tests the PR using a custom icon with the <Info> components

feat(docs): update callouts to include icon attribute

---

packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v4.ts
packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts

Fixes issue where i cannot run `/revalidate-all/v3` or `/revalidate-all/v4` on partially authed docs.

fix: revalidate all should not be gated

---

.github/workflows/deploy-fern-bot-dev.yml
servers/fern-bot/src/functions/stale-notifs/actions/sendStaleNotifications.ts

As well as clean up console logs

chore(fern-bot): make the stale notifs lambda use a fern-dev fern token

---

packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/callback.ts

Before this PR: redirects on proxied domains are getting sent to `app.buildwithfern.com` instead of the `x-fern-host` location. This is pretty difficult to catch from an ete test so the following cases need to be considered in the future:
- xxx.docs.staging.buildwithfern.com -> x-fern-host is respected
- xxx.docs.buildwithfern.com -> x-fern-host is respected
- custom domain using subpath proxy -> x-fern-host is respected
- vercel.app preview url -> x-fern-host is NOT considered
- custom domain without subpath proxy -> x-fern-host is NOT considered
- localhost development -> x-fern-host is NOT considered

fix: correct redirect host for proxied domains in auth

---

packages/ui/docs-bundle/src/middleware.ts
packages/ui/fern-docs-edge-config/src/getCanonicalHost.ts
packages/ui/fern-docs-edge-config/src/index.ts

Attempt to fix:
- https://www.courier.com/docs/rest/sitemap.xml
- https://primer.io/docs/api/sitemap.xml
- https://www.assemblyai.com/docs/api-reference/sitemap.xml

fix: set the canonical url manually for subpath customers that are not setting x-fern-host

---

packages/ui/docs-bundle/src/middleware.ts
packages/ui/fern-docs-edge-config/src/getCanonicalHost.ts
packages/ui/fern-docs-edge-config/src/index.ts

Reverts fern-api/fern-platform#1610

Revert "fix: set the canonical url manually for subpath customers that are not setting x-fern-host"

---

fern/apis/fdr/definition/api/latest/type.yml
packages/fdr-sdk/src/api-definition/__test__/unwrap.test.ts
packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/latest/resources/type/types/ObjectType.ts
servers/fdr/src/api/generated/api/resources/api/resources/latest/resources/type/types/ObjectType.d.ts

Fixes FER-3361
- Adds `extraProperties` to `ObjectType` in fdr, which allows the plumbing of a value type for `Map<string, valueType>` for use with UI downstream
- `extraProperties` is typed as an `optional<TypeReference>`, since it is either a discrete shape, or `Unknown` type (both handled by existing visitors in UI
- Product Demo
WIP to be pushed to FDR dev for testing

feat: update fdr types to accomodate extra properties type reference

---

packages/ui/app/src/atoms/launchdarkly.ts
packages/ui/app/src/mdx/components/launchdarkly/LaunchDarkly.tsx

```
<LaunchDarkly flag="flag-a">
Show this if flag-a is true
</LaunchDarkly>
```
```
<LaunchDarkly not flag="flag-a">
Show this if flag-a is false
</LaunchDarkly>
```
```
<LaunchDarkly not flag="flag-b" equals="some-string">
Show this if flag-b does not equal "some-string"
</LaunchDarkly>
```

feat: launchdarkly not syntax

---

.github/workflows/publish-fdr-sdk.yml

- Add publish step for core utils in CI script
- Unblock FDR publishing
- To be tested

fix: add publish step for lockstepped core utils

---

packages/commons/core-utils/package.json

Removes private flag for public publishing

fix: remove private flag from package json

---

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/ory/callback.ts
packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/LoadDocsPerformanceTracker.ts
packages/ui/docs-bundle/src/server/auth/FernJWT.ts
packages/ui/docs-bundle/src/server/authProps.ts
packages/ui/docs-bundle/src/server/getDocsPageProps.ts
packages/ui/fern-docs-auth/src/types.ts

if the jwt payload is empty or has a different schema, don't throw.

fix: make jwt parsing less strict

---

packages/commons/core-utils/src/withDefaultProtocol.ts
packages/ui/app/src/hooks/useStandardProxyEnvironment.ts
packages/ui/app/src/seo/getBreadcrumbList.ts
packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/jwt/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/auth/logout.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/changelog.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/integrations/launchdarkly/identify.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/ory/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/oauth/webflow/callback.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/robots.txt.ts
packages/ui/docs-bundle/src/server/getUnauthenticatedRedirect.ts
packages/ui/docs-bundle/src/server/safeUrl.ts
packages/ui/docs-bundle/src/server/xfernhost/edge.ts
packages/ui/fern-docs-auth/src/types.ts

Allow configuring a logout redirect page in jwt token auth.
Also in this PR:
- improved devx when testing auth redirects
- todo's in places where we're not doing enough input validation

fix: logout, then redirect to configured url

---

packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/loadWithUrl.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts

Fixes compile break caused by https://github.com/fern-api/fern-platform/pull/1621

fix: compile break

---

fern/apis/fdr/generators.yml

- Add branded aliases to fern-cjs-sdk
- Resolve compiler errors on fern side
- Manually generated

fix: add branded aliases to fern-cjs-sdk

---

packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/getDynamicDocsPageProps.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts

Note: authProps.token always has a prefix `(like custom_)`

fix: inconsistent deserialization of authprops

---

packages/fdr-sdk/src/navigation/utils/pruneNavigationTree.ts
packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/__test__/withBasicTokenViewAllowed.test.ts
packages/ui/docs-bundle/src/server/auth/checkViewerAllowed.ts
packages/ui/docs-bundle/src/server/withBasicTokenAnonymous.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts
packages/ui/fern-docs-auth/src/types.ts

Introduces a new `anonymous` path filter which:
- if the user is anonymous, these pages will be visible
- if the user is authenticated, these pages will be hidden, but not pruned
Also in this pr:
- prune the sidebar nodes so that hidden pages are stripped away from initial props.

feat: anonymous filtering in jwt token

---

fern/apis/fdr/generators.yml
packages/fdr-sdk/src/api-definition/unwrap.ts
packages/ui/app/src/api-reference/types/discriminated-union/DiscriminatedUnionVariant.tsx
packages/ui/app/src/api-reference/types/type-reference/InternalTypeReferenceDefinitions.tsx
packages/ui/app/src/playground/PlaygroundWebSocketHandshakeForm.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointForm.tsx
packages/ui/app/src/playground/form/PlaygroundDescriminatedUnionForm.tsx
packages/ui/app/src/playground/form/PlaygroundObjectPropertyForm.tsx
packages/ui/app/src/playground/form/PlaygroundTypeReferenceForm.tsx
packages/ui/app/src/resolver/ApiEndpointResolver.ts
packages/ui/app/src/resolver/ApiTypeResolver.ts
packages/ui/app/src/resolver/__test__/__snapshots__/ApiDefinitionResolver.test.ts.snap
packages/ui/app/src/resolver/types.ts

Fixes FER-3363
- Adds small markdown based marker for objects with additional properties in API reference
- Adds Map of string to string for additional properties in the playground
- Live updates the playground payload, enabling for send-request
- Persists state of additional properties via atom and subtraction
- Customer Demos
https://github.com/user-attachments/assets/7397fc5e-fdb7-439f-99c2-d7ca28c26617

feat: additional properties UX

---

packages/ui/app/src/atoms/apis.ts
packages/ui/app/src/util/scrollToCenter.ts

Turns out offsetParent isn't always the immediate parent, but the one where offset is non-zero. If the while loop goes beyond the container, stop traversing.

fix: scrollToCenter offsetTop/offsetParent behavior

---

packages/ui/app/src/api-reference/endpoints/EndpointContentCodeSnippets.tsx

errors was previously rendered form ErrorsV1, but when we switched to ErrorsV2, ErrorsV2 nested the value in the following way:
```
{
"type": "json",
"value": "my-value"
}
```
this pr changes it to render:
```
"my-value"
```

fix: render error snippet without json wrapper

---

packages/ui/app/src/api-reference/endpoints/EndpointParameter.tsx
packages/ui/app/src/api-reference/types/discriminated-union/DiscriminatedUnionVariant.tsx
packages/ui/app/src/api-reference/types/object/ObjectProperty.tsx
packages/ui/app/src/mdx/Markdown.tsx

Naively fixes duplicate description bug by choosing only the first description to show. Logs >1 description issues to posthog.

fix: prefer the first description when multiple are detected

---

servers/fdr/src/__test__/mock.ts
servers/fdr/src/__test__/unit-tests/generate-algolia-search-records/testGenerateAlgoliaSearchRecordsForDocs.test.ts
servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts
servers/fdr/src/services/algolia/AlgoliaSearchRecordGenerator.ts
servers/fdr/src/services/algolia/AlgoliaSearchRecordGeneratorV2.ts
servers/fdr/src/services/algolia/AlgoliaService.ts

Cache endpoints in the `fern-docs/api-definition` route. 
Make loading playground faster.
Will test on dev

fix: make sure endpoints are cached in nextjs route on register

---

.github/workflows/deploy-docs-bundle-preview.yml
clis/vercel-scripts/src/utils/deployer.ts
packages/ui/app/src/atoms/launchdarkly.ts
packages/ui/app/src/header/Header.tsx
packages/ui/app/src/hooks/useApiRoute.ts
packages/ui/app/src/hooks/useApiRouteSWR.ts
packages/ui/app/src/hooks/useInterceptNextDataHref.ts
packages/ui/app/src/playground/hooks/useEndpointContext.ts
packages/ui/app/src/playground/hooks/useWebSocketContext.ts
packages/ui/app/src/search/SearchDialog.tsx
packages/ui/app/src/search/algolia/useAlgoliaSearchClient.ts
packages/ui/app/src/search/cohere/CohereChatButton.tsx
packages/ui/app/src/search/inkeep/useInkeepSettings.ts
packages/ui/app/src/services/useApiKeyInjectionConfig.ts
packages/ui/app/src/services/useSearchService.ts
packages/ui/app/src/sidebar/SidebarSearchBar.tsx
packages/ui/app/src/util/withSkewProtection.ts
packages/ui/docs-bundle/next.config.mjs

**Problem 1**: when you run `vercel build` then `vercel deploy --prebuilt`, we don't actually get access to any of the vercel-specific environment variables, e.g. `VERCEL_DEPLOYMENT_ID` or `VERCEL_ENV` at built-time. So, we needed to switch the deployment model such that source files are uploaded to vercel so that vercel build the deployment directly.
**Problem 2**: nextjs (perhaps because we're using a fork of nextjs?) is not correctly setting the x-deployment-id header in the prefetch requests. to circumvent this, we're appending `?dpl=${process.env.NEXT_DEPLOYMENT_ID}` to all prefetch requests from the router. This will force skew protection on prefetching!
**Problem 3**: all other fetch requests to `/api/fern-docs/*` must have the `x-deployment-id` header set to leverage skew …

fix: skew protection

---

.github/workflows/deploy-docs-bundle-preview.yml
packages/commons/next-seo/package.json
packages/ui/app/package.json
packages/ui/app/src/components/FernLink.tsx
packages/ui/app/src/hooks/useApiRouteSWR.ts
packages/ui/app/src/hooks/useInterceptNextDataHref.ts
packages/ui/app/src/util/withSkewProtection.ts
packages/ui/docs-bundle/next.config.mjs
packages/ui/docs-bundle/package.json
packages/ui/fern-docs-utils/package.json
packages/ui/fontawesome-cdn/package.json
packages/ui/local-preview-bundle/package.json
pnpm-lock.yaml
test/docs-e2e/nginx-proxy/index.test.ts
test/docs-e2e/skew-protection/index.test.ts
test/utils/deployment-url.ts

Link to fix in our fork of next.js: https://github.com/fern-api/next.js/commit/0e4d20b070cdcf44a606b42d13c50de37530774f

fix: skew protection on prefetch without interfering with proxy

---

fern/apis/fdr/generators.yml
packages/ui/fern-dashboard/src/lib/utils.ts

This PR fixes the failing CI for the fiddle SDK generation.

fix: sdk generation for fiddle not working

---

packages/commons/next-seo/package.json
packages/ui/app/package.json
packages/ui/docs-bundle/next.config.mjs
packages/ui/docs-bundle/package.json
packages/ui/fern-docs-utils/package.json
packages/ui/fontawesome-cdn/package.json
packages/ui/local-preview-bundle/package.json
pnpm-lock.yaml

adds a feature flag that always hard navigates on 404.
- fixes issue where a proxied site's client router is unaware that the forward proxy owns a subset of routes
- fixes issue where after 12 hours of version skew protection, the client has to refresh the page.
https://github.com/vercel/next.js/pull/71198

fix: hard navigate on 404

---

packages/ui/app/src/analytics/posthog.ts
packages/ui/app/src/index.ts
packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/pages/404.tsx
packages/ui/docs-bundle/src/server/extractNextDataPathname.ts

Addendum to https://github.com/fern-api/fern-platform/pull/1663 fix, which doesn't work because the middleware is not correctly matching and rewriting on /404.json when the project contains an additional basepath.

fix: rewrite 404 in middleware

---

packages/ui/app/src/api-reference/endpoints/EndpointError.tsx

This PR aligns the error description to the left to avoid the centering bug reported by @abvthecity

chore(docs): error text align

---

packages/ui/app/src/changelog/index.scss

This is a styling fix to make the changelog mobile-friendly

chore(docs): changelog mobile friendly

---

packages/ui/app/src/playground/PlaygroundDrawer.tsx

This PR updates the API Playground header styling for mobile. 
Before: 
(Ignore the error - this is due to the testing environment and is not related to the styling)
After:

chore(docs): update mobile playground header

---

.github/workflows/ci.yml
packages/template-resolver/src/ResolutionUtilities.ts
packages/template-resolver/src/SnippetTemplateResolver.ts
packages/template-resolver/src/UnionResolver.ts
packages/template-resolver/src/__test__/unit-tests/assets/imdbApiDefinition.ts

Template resolver is used for our Snippets SDK and was failing to compile
This adds compile checking to CI + fixes bugs
Compile step added to CI/Cd

chore: template resolver compiles

---

package.json
packages/ui/app/src/playground/PlaygroundDrawer.tsx
packages/ui/app/src/playground/PlaygroundWebSocketSessionForm.tsx

- Takes only last 25 websocket records when showing messages.
- This is a temporary measure until proper pagination can be added.
- Furthermore, rendering of messages can be made much better since there are a lot of components being re-rendered.
- Customer performance issue
https://github.com/user-attachments/assets/34f2f23e-e9f8-4c25-a4bb-afa4c427d981

fix: take last 25 websocket records

---

servers/fdr/src/db/snippets/SnippetTemplate.ts

Setting `undefined` for a property that should not be set

fix(snippets): actually return api definition ids

---

fern/apis/generator-cli/generators.yml

This brings the generator CLI Python SDK to a version that is Pydantic  v2 compatible

bump generator cli python generator version

---

pnpm-lock.yaml
servers/fern-bot/src/functions/generator-updates/shared/updateGeneratorInternal.ts

Fixes FER-3388
We will sometimes run the auto-upgrader on an SDK repo, which is not correct, and actually confusing for users
This PR skips any workspaces that have the `.mock` directory, which is what we'd try to upgrade within an SDK repo

chore: do not run fern-bot upgrader on SDK repos directly

---

servers/fdr/src/__test__/local/setupMockFdr.ts
servers/fdr/src/app/FdrApplication.ts

- increases global timeout on prisma to 15s
- prisma timeouts for large docs generation
- to be tested with fdr

fix: globally increase prisma timeout to 15s

---

packages/ui/app/src/components/FernErrorBoundary.tsx
packages/ui/app/src/mdx/bundlers/mdx-bundler.ts
packages/ui/app/src/mdx/bundlers/next-mdx-remote.ts
packages/ui/app/src/mdx/components/index.tsx
packages/ui/fern-docs-mdx/src/__test__/__snapshots__/landing-page.mdx
packages/ui/fern-docs-mdx/src/__test__/fixtures/landing-page.mdx
packages/ui/fern-docs-mdx/src/__test__/sanitize-fixtures.test.ts
packages/ui/fern-docs-mdx/src/parse.ts
packages/ui/fern-docs-mdx/src/plugins/__test__/remark-sanitize-acorn.test.ts
packages/ui/fern-docs-mdx/src/plugins/rehype-acorn-error-boundary.ts
packages/ui/fern-docs-mdx/src/plugins/remark-sanitize-acorn.ts

rehype-sanitize-acorns is over-sanitizing markdown
```
export const cards = ["test"];
cards.map(elem => <div>{elem}</div>);
```
was getting sanitized because `elem` was getting matched.

fix: reduce aggressive mdx sanitization

---

packages/fdr-sdk/src/converters/db/convertDocsDefinitionToDb.ts

Forgot to migrate getReferencedApiDefinitions in FDR.

fix: get referenced api definitions in register v2 types

---

packages/ui/app/src/css/utilities.scss

This PR has not been tested. 
Resolves an issue reported by Vapi with the banner component:
I added the same styling as custom CSS to Vapi's style sheet to fix:
[style](https://github.com/VapiAI/fern/blob/04614aeae2b95eb576cebe8b6f2eb9850ccb40c4/fern/assets/styles.css#L116-L118)

chore(doc): update banner styling

---

packages/fdr-sdk/src/navigation/utils/toRootNode.ts

This change guarantees that `pointsTo` is always set. (The CLI does not set the pointsTo field.)

fix: update points-to property because it's not always set

---

.github/workflows/playwright.yml
packages/commons/core-utils/src/withDefaultProtocol.ts
packages/fdr-sdk/src/__test__/__snapshots__/no-version-no-tabs.test.ts.snap
packages/fdr-sdk/src/__test__/__snapshots__/no-version-yes-tabs.test.ts.snap
packages/fdr-sdk/src/__test__/__snapshots__/octoai.test.ts.snap
packages/fdr-sdk/src/__test__/__snapshots__/polytomic.test.ts.snap
packages/fdr-sdk/src/navigation/utils/__test__/followRedirects.test.ts
packages/fdr-sdk/src/navigation/utils/findNode.ts
packages/fdr-sdk/src/navigation/utils/followRedirect.ts
packages/ui/app/src/analytics/posthog.ts
packages/ui/app/src/mdx/components/if/If.tsx
packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/__test__/withRbac.test.ts
packages/ui/docs-bundle/src/server/auth/getAuthState.ts
packages/ui/docs-bundle/src/server/handleLoadDocsError.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts
packages/ui/docs-bundle/src/server/withPrunedNavigation.ts
packages/ui/docs-bundle/src/server/withRbac.ts
packages/ui/docs-bundle/src/server/xfernhost/node.ts

- Returns ALLOW or DENY instead of true/false
- fixes case where all requests are blocked in the middleware. We're not quite ready for that yet.
https://appbuildwithfern-3uuora74q-buildwithfern.vercel.app/api/fern-docs/preview?host=test-jwt-auth-smokey.docs.buildwithfern.com

fix: make rbac rules more clear and unblock public pages

---

packages/ui/app/src/playground/PlaygroundWebSocket.tsx
packages/ui/app/src/search/SearchHits.tsx
packages/ui/app/src/search/content/EndpointRecordV4.tsx
packages/ui/app/src/search/content/FieldRecordV1.tsx
packages/ui/app/src/search/content/MarkdownSectionRecordV1.tsx
packages/ui/app/src/search/content/PageRecordV4.tsx

* removes block labels
* moves expand button to bottom right
* unblock go-lives

fix: small search papercuts

---

packages/fdr-sdk/src/__test__/fixtures.test.ts
packages/fdr-sdk/src/__test__/testGetAllUrlsFromDocsConfig.ts
packages/fdr-sdk/src/navigation/NodeCollector.ts
packages/healthchecks/src/rules/all-pages-load/rule.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v4.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/sitemap.xml.ts

**Problem**: authed pages were being needlessly revalidated
**Why this regressed**: the predicate used for filtering out authed pages was recently changed to setting `authed: true`, and so it wasn't filtered out from the revalidation logic.
**What is the impact**: revalidation will make `HEAD` requests to the redirect target, which for authed pages tend to be the customer's servers. This results in a DDoS on their servers.
**Solution**: filtering out `authed: true` pages from the node collector

fix: filter out authed pages from collector

---

packages/ui/app/src/playground/endpoint/PlaygroundEndpointAliasForm.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointForm.tsx
packages/ui/app/src/playground/form/PlaygroundAdditionalProperties.tsx
packages/ui/app/src/playground/form/PlaygroundDescriminatedUnionForm.tsx
packages/ui/app/src/playground/form/PlaygroundListForm.tsx
packages/ui/app/src/playground/form/PlaygroundMapForm.tsx
packages/ui/app/src/playground/form/PlaygroundObjectForm.tsx
packages/ui/app/src/playground/form/PlaygroundObjectPropertyForm.tsx
packages/ui/app/src/playground/form/PlaygroundTypeReferenceForm.tsx

Fixes FER-3440
* fixes ping pong behavior between dual callbacks that leads to deferred state not picking up the right update during render step
* Customer regression
https://github.com/user-attachments/assets/3316ea70-3004-4d88-9d5a-4adf640bafdf

fix: ping-pong behavior of use callback which messes with deferred state

---

packages/fdr-sdk/src/converters/db/convertAPIDefinitionToDb.ts

We shouldnt fail hard on server urls being wrong in the spec.
Some customers experienced errors generating docs. 
N/A (test on dev)

fix(fdr): dont fail hard on bad server urls

---

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/logout.ts
packages/ui/docs-bundle/src/server/auth/workos-session.ts

Before: the logoutUrl generated by workos doesn't delete cookies, and it always redirects to buildwithfern.com

fix: logout url for sso

---

packages/ui/app/src/resolver/resolveMarkdownPage.ts

This PR updates the indicator we search for to render a page with an `<Aside>`.
Properly rendering a page with an `<Aside>` within code but no actual `<Aside>
Properly rendering a page with an actual `<Aside>`

fix(docs): update how we parse for asides

---

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/logout.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/preview.ts
packages/ui/docs-bundle/src/server/auth/with-secure-cookie.ts
packages/ui/docs-bundle/src/server/xfernhost/edge.ts
packages/ui/docs-bundle/src/server/xfernhost/node.ts

1) fern_token cookie isn't being deleted upon logout because we're not setting its `domain` and `path` values.
2) this pr fixes how the `getHostNode` and `getHostEdge` works:
- when the user is loading docs from `docs.domain.com`, the host should be `docs.domain.com`
- when the user is loading docs from `buildwithfern.com/learn` the host should be `buildwithfern.com` (even though it's actually proxied to app.buildwithfern.com)
- when the user is loading docs from a preview or staging url, such as `x.docs.staging.buildwithfern.com`, the host should be `x.docs.staging.buildwithfern.com`
- when the user is loading docs via a PR preview link, the host is still `xxx.vercel.app` because the `__fern_preview_host` cookie should be ignore.
This is done via
1. check if x-fern-host header exists. If …

fix: correctly delete logout cookie

---

packages/ui/docs-bundle/src/pages/api/fern-docs/auth/api-key-injection.ts
packages/ui/fern-docs-auth/src/types.ts

Adds a `fern.api_key` claim for injecting api keys into the api playground.

feat: enable api key injection from within JWT

---

packages/ui/docs-bundle/src/pages/static/[domain]/[[...slug]].tsx
packages/ui/docs-bundle/src/server/withMiddlewareRewrite.ts
packages/ui/docs-bundle/src/server/withPathname.ts

In ISR, the getStaticProps function doesn't have access to the node request that made it, so it's not possible to get the `req.headers.host` from it. Here, we'll use query parameters to inject the current `host` into the params.
This will stabilize the login/logout urls generated in the app-staging.buildwithfern.com environment.

fix: append host to query params on isr in the middleware

---

packages/fdr-sdk/src/__test__/output/humanloop/apiDefinitions.json
packages/fdr-sdk/src/__test__/output/hume/apiDefinitions.json
packages/fdr-sdk/src/__test__/output/octoai/apiDefinitions.json
packages/fdr-sdk/src/__test__/output/polytomic/apiDefinitions.json
packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts

Fixes FER-3461 FER-3462
* Does not set name for example snippet for js or ts snippets in FDR. Example generation prefers snippet names, so this aligns with other languages
* Customer reported bugs
* To be tested on staging site (on Mercoa)

found needle in haystack that is overwriting name

---

servers/fdr/.env.dev
servers/fdr/.env.prod

Allows the prisma client to add a connection up to 6 on prod and 4 on dev (current default is 3). 
There are certain db queries that are failing because there are no connections that free up in ~10 seconds. 
Will test on dev.

fix(fdr): increase connection limit to support parallel writes

---

packages/ui/docs-bundle/src/server/auth/getAuthState.ts
packages/ui/docs-bundle/src/server/auth/workos-user-to-fern-user.ts

This is designed only to work with staging for now. This is a follow up of https://github.com/fern-api/fern-platform/pull/1770 but can be merged before #1770 is merged, since the staging environment (https://rbac.ferndocs.dev) has already been stood up.
Idea behind this is that RBAC is store in WorkOS FGA.

feat: fga-based workos rbac

---

packages/fdr-sdk/src/navigation/utils/findNode.ts
packages/ui/docs-bundle/src/server/withRbac.ts

Fixes two issues:
1. edge nodes are set as "authed=true" even though they're not:
2. fixes how fdr-sdk treats the final redirect fallback (it should treat the fallback redirect as a "notFound" so that it can be properly handled by the auth check)

fix: how authed edge nodes and redirects are computed

---

packages/ui/app/src/header/Header.tsx
packages/ui/app/src/sidebar/SidebarSearchBar.tsx

This PR adds an id to Fern's searchbar so it is easier to integrate with Inkeep

feat(docs): add id to search

---

packages/fdr-sdk/src/navigation/utils/pruneNavigationTree.ts
packages/fdr-sdk/src/navigation/versions/latest/NavigationNodeWithRedirect.ts
packages/fdr-sdk/src/utils/traversers/prunetree.ts
packages/ui/docs-bundle/src/server/__test__/withRbac.test.ts
packages/ui/docs-bundle/src/server/withInitialProps.ts

This fixes an edge case where, lets say, you have a few version nodes, which contains unauthed children, or you have orphaned children that are visible to "everyone".

fix: don't mark parent edges as authed=true if it contains children that are authed=false

---

pnpm-lock.yaml
servers/fdr/package.json
servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts
servers/fdr/src/server.ts

* Sets global dispatcher timeout to 5s.
* Adds a log line to give the reason for failure if it is not that.
* Consistent failures when trying to deploy from fdr-dev
* To be tested

fix: set global dispatcher timeout to 5s 

---

packages/fdr-sdk/src/api-definition/snippets/curl.test.ts
packages/fdr-sdk/src/api-definition/snippets/curl.ts

fix: strip out nulls in url encoded curl

---

servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts

Improves telemetry for failing fetch so that we can understand what is going on a bit better

fix: print full error stack in message where fetch is failing

---

packages/ui/docs-bundle/src/pages/api/fern-docs/org/org-for-url.ts

`app-dev` was defaulting to hitting prod
allows us to do end-to-end testing of the endpoint on dev
will test on dev

fix: instantiate fdr client with `NEXT_PUBLIC_FDR_ORIGIN`

---

packages/ui/docs-bundle/src/server/auth/getAuthState.ts
packages/ui/fern-docs-edge-config/src/__test__/isPreviewDomain.test.ts
packages/ui/fern-docs-edge-config/src/getPreviewUrlAuthConfig.ts
packages/ui/fern-docs-edge-config/src/index.ts

Add edge config for authed previews. 
Some customers dont want their preview urls to be public.
Unit tests for checking if a domain is a "preview" domain

feat(docs): add edge config for authed previews

---

packages/ui/docs-bundle/src/pages/api/fern-docs/org/org-for-url.ts
packages/ui/docs-bundle/src/server/auth/getAuthState.ts
packages/ui/docs-bundle/src/server/auth/metadata-for-url.ts
packages/ui/fern-docs-edge-config/src/getPreviewUrlAuthConfig.ts
packages/ui/fern-docs-server/src/DocsLoader.ts

Tests authed previews using local dev: 
1) stop using regex to figure out if a preview URL and instead use KV
2) add a timeout when loading from raw FDR
Making sure docs previews are behind auth if configured
Tested locally

fix: authed previews works

---

packages/ui/docs-bundle/src/server/auth/getAuthState.ts

Authed Preview URL shoudl redirect to the right URL
Support authed preview urls
Will test on dev

fix: make sure authorization url had state

---

packages/ui/docs-bundle/src/server/auth/getAuthState.ts
packages/ui/docs-bundle/src/server/auth/workos-handler.ts

In production, we should redirect to `app.buildwithfern.com` 
Make sure redirect URIs work in production WorkOS auth
N/A

fix: authed previews in production redirect to the CDN URI

---

fern/apis/fdr/definition/navigation/latest/__package__.yml
fern/apis/fdr/definition/navigation/v1/__package__.yml
packages/fdr-sdk/src/client/generated/api/resources/docs/resources/v1/resources/write/client/Client.ts
packages/fdr-sdk/src/client/generated/api/resources/docs/resources/v1/resources/write/client/requests/RegisterDocsRequest.ts
packages/fdr-sdk/src/client/generated/api/resources/docs/resources/v2/resources/write/client/Client.ts
packages/fdr-sdk/src/client/generated/api/resources/docs/resources/v2/resources/write/client/requests/RegisterDocsRequest.ts
packages/fdr-sdk/src/client/generated/api/resources/navigation/resources/latest/types/RootNode.ts
packages/fdr-sdk/src/client/generated/api/resources/navigation/resources/v1/types/RootNode.ts
packages/fdr-sdk/src/navigation/migrators/v1ToV2.ts
packages/fdr-sdk/src/navigation/versions/v1/converters/NavigationConfigConverter.ts
packages/fdr-sdk/src/navigation/versions/v1/converters/toRootNode.ts
packages/ui/docs-bundle/src/server/auth/getAuthState.ts
servers/fdr/src/api/generated/api/resources/navigation/resources/latest/types/RootNode.d.ts
servers/fdr/src/api/generated/api/resources/navigation/resources/v1/types/RootNode.d.ts

* plumbs through an optional roles property to give the full set of roles available for use in docs
* dependency for encoding permissions
* optional for now, to not create a breaking change with back-compat (can potentially think about making required in future)
* show how we can segment algolia search records based on RBAC
* to be tested in toy app for search v3

chore: plumb roles through root node for consumption with generating roles in search records

---

packages/ui/app/src/playground/WithLabel.tsx
packages/ui/app/src/playground/form/PlaygroundTypeReferenceForm.tsx
packages/ui/app/src/type-shorthand/index.tsx
packages/ui/components/src/FernInput.scss
packages/ui/components/src/FernInput.tsx
packages/ui/components/src/FernNumericInput.tsx

The API Playground labels look awful but keeping it as is until we find time to refactor it.

fix: render min max values

---

packages/ui/app/src/playground/auth/PlaygroundOAuthForm.tsx
packages/ui/app/src/playground/code-snippets/resolver.ts
packages/ui/app/src/playground/endpoint/PlaygroundEndpointContent.tsx
packages/ui/app/src/playground/utils/auth-headers.ts
packages/ui/app/src/playground/utils/oauth.ts
packages/ui/app/src/playground/utils/should-render-auth.ts

When the oauth scheme is present, the referenced endpoint should NOT render the oauth scheme since it's self-referential.

fix: oauth ignores auth in playground

---

fern/apis/generator-cli/generators.yml

Union utils is broken on the latest python generator.

chore(generator-cli): remove `union-utils` from sdk generation

---

packages/ui/app/src/api-reference/endpoints/CodeExampleClientDropdown.tsx
packages/ui/app/src/api-reference/endpoints/EndpointContent.tsx
packages/ui/app/src/api-reference/endpoints/EndpointContentCodeSnippets.tsx
packages/ui/app/src/api-reference/endpoints/EndpointContentLeft.tsx
packages/ui/app/src/api-reference/endpoints/EndpointExampleSegmentedControl.tsx
packages/ui/app/src/api-reference/endpoints/ErrorExampleSelect.tsx
packages/ui/app/src/api-reference/endpoints/example-groups.ts
packages/ui/app/src/api-reference/endpoints/useExampleSelection.ts
packages/ui/app/src/api-reference/examples/code-example.ts
packages/ui/app/src/api-reference/examples/example-groups.ts
packages/ui/app/src/api-reference/types/EndpointContent.tsx
packages/ui/app/src/atoms/lang.ts
packages/ui/app/src/mdx/components/client-libraries/ClientLibraries.tsx
packages/ui/app/src/mdx/components/snippets/EndpointRequestSnippet.tsx
packages/ui/app/src/mdx/components/snippets/EndpointResponseSnippet.tsx
packages/ui/app/src/mdx/components/snippets/utils.tsx

- rewrote the logic that generates the complex input shape for code snippets
- key by request code, and dedupe by response json
- added plenty of redundancies in "selecting" the code example, so that it should never fail to resolve a request/response shape despite external influences (i.e. local storage, which was previously causing examples to disappear)
- clicking outside of the errors block will deselect the error snippet on the right
- slightly improved the rendering of the select dropdown

fix: error example dropdown issues

---

packages/ui/app/src/playground/auth/PlaygroundAuthorizationFormCard.tsx
packages/ui/app/src/playground/auth/PlaygroundCardTriggerApiKeyInjected.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointForm.tsx

- header fields in the api playground passed in the wrong "value" field, which made it impossible to type and update the header state
- if the injected api key is `""`, don't treat it as "logged in"
- when clicking "reset", reset not only the bearer token but also the user-entered bearer token

fix: header fields in the api playground, and resetting user-entered token

---

packages/ui/app/src/api-reference/endpoints/EndpointUrl.tsx
packages/ui/app/src/atoms/apis.ts
packages/ui/app/src/atoms/docs.ts
packages/ui/app/src/components/ApiReferenceButton.tsx
packages/ui/app/src/mdx/components/snippets/EndpointRequestSnippet.tsx
packages/ui/app/src/mdx/components/snippets/EndpointResponseSnippet.tsx
packages/ui/app/src/mdx/components/snippets/useFindEndpoint.tsx
packages/ui/app/src/resolver/DocsContent.ts
packages/ui/app/src/resolver/resolveMarkdownPage.ts
packages/ui/app/src/util/processRequestSnippetComponents.ts

Before this PR: the request/response snippet selector will ignore endpoint pairs, always selecting the first encountered endpoint (usually stream, not batch)
After this PR: the request/response snippet selector will consider the provided example name when selecting for the relevant endpoint
Also in this PR
- fix regression in rendering basepath in endpoint snippet title
- restore backlink to api reference

fix: request response snippet resolver should work for endpoint pairs (stream/batch)

---

packages/ui/app/src/api-reference/endpoints/EndpointUrl.tsx

regression introduced in https://github.com/fern-api/fern-platform/pull/1818 was adding an additional `/` to the beginning of each endpoint

fix: basepath regression

---

packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/markdown.ts
packages/ui/docs-bundle/src/server/removeLeadingSlash.ts

Allow appending `.md` or `.mdx` at the end of any markdown page (the extension depends on the format of the original markdown file) to view the markdown content.
- strips away the frontmatter, but append the title to the top using `#`
- caches for 60 seconds

feat: support raw markdown

---

packages/ui/docs-bundle/src/middleware.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/llms-full.txt.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/llms.txt.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/markdown.ts
packages/ui/docs-bundle/src/server/getSectionRoot.ts
packages/ui/docs-bundle/src/server/getStringParam.ts
packages/ui/docs-bundle/src/server/llm-txt-md.ts
packages/ui/fern-docs-mdx/src/strip-util.ts

Introduces 2 new api routes based on the https://llmstxt.org/ specification.
- llms.txt -> a directory of all markdown files + landing page
- llms-full.txt -> concatenation of all markdown pages
Included in this PR:
- titles and descriptions are extracted from all markdown page frontmatters, and stitched back together
- content of landing pages will always be included in `llms.txt`
Not included in this PR:
- no support for api endpoint markdown -> need way to represent api endpoint definition as markdown, with links to code examples.
- no support for markdown snippets or code snippets -> CLI/FDR needs to store more metadata about code snippets and we need to decide what the pathname is.

feat: llms.txt

---

packages/ui/app/src/atoms/playground.ts
packages/ui/app/src/playground/WithLabel.tsx
packages/ui/app/src/playground/auth/PlaygroundCardTriggerManual.tsx
packages/ui/app/src/playground/auth/PlaygroundHeaderAuthForm.tsx
packages/ui/app/src/playground/code-snippets/resolver.ts
packages/ui/app/src/playground/endpoint/PlaygroundEndpoint.tsx
packages/ui/app/src/playground/endpoint/PlaygroundEndpointForm.tsx
packages/ui/app/src/playground/form/PlaygroundObjectPropertyForm.tsx
packages/ui/app/src/playground/types/auth.ts
packages/ui/app/src/playground/utils/auth-headers.ts
packages/ui/app/src/playground/utils/endpoints.ts
packages/ui/app/src/playground/utils/header-key-case.ts
packages/ui/app/src/playground/utils/websocket.ts
packages/ui/app/src/type-shorthand/index.tsx
packages/ui/fern-docs-auth/src/types.ts

part 1 / 2: enable injection of initial values in playground via JWT

feat: api playground state injection

---

fern/apis/fdr/definition/api/v1/read/__package__.yml
fern/apis/fdr/definition/api/v1/register/__package__.yml
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/read/types/OAuthClientCredentialsReferencedEndpoint.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/types/OAuthClientCredentialsReferencedEndpoint.ts
servers/fdr/src/api/generated/api/resources/api/resources/v1/resources/read/types/OAuthClientCredentialsReferencedEndpoint.d.ts
servers/fdr/src/api/generated/api/resources/api/resources/v1/resources/register/types/OAuthClientCredentialsReferencedEndpoint.d.ts

* Infra for plumbing necessary values for manipulating OAuth Client credential values
* customer asks
To be tested on CLI side

plumb OAuth header key and token prefix

---

packages/ui/docs-bundle/src/pages/api/fern-docs/llms-full.txt.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/llms.txt.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/markdown.ts
packages/ui/docs-bundle/src/server/DocsLoader.ts
packages/ui/docs-bundle/src/server/getMarkdownForPath.ts
packages/ui/docs-bundle/src/server/headerKeyCase.ts
packages/ui/fern-docs-server/src/ApiDefinitionLoader.ts

this PR hacks together request code snippets for endpoints to a structured markdown textfile consumed in llms.txt

fix: llms-txt with code snippets

---

packages/fdr-sdk/src/__test__/output/astronomer/node.json
packages/fdr-sdk/src/navigation/versions/v1/converters/ChangelogConverter.ts
packages/fdr-sdk/src/navigation/versions/v1/converters/__test__/groupByTime.test.ts

* fixes bug where changelog records were rendering with 1900
* some changelogs were rendering 1900 as the year in which they were created, this is not correct
* requires FDR update

fix: changelog converter uses real year

---

packages/ui/app/src/api-reference/endpoints/EndpointContentLeft.tsx
packages/ui/fern-docs-server/src/getHarRequest.ts
servers/fdr/docker-compose.ete.yml

* Very small fix to plumb the headerKey and tokenPrefix to various locations where the oAuth scheme is visited
* preemptive
* local docs dev

chore: plumb OAuth Client Credentials header name and token prefix

---

packages/ui/components/src/FernCard.scss

fixes alignment of list items inside of cards
before: 
after:

fix(docs): li in card

---

packages/ui/docs-bundle/src/pages/api/fern-docs/search/v2/reindex.ts

reindexing is currently throwing a 500 because it's passing the staging url to FDR, which doesn't exist.

fix: without staging

---

packages/ui/local-preview-bundle/package.json
packages/ui/local-preview-bundle/tailwind.config.js
pnpm-lock.yaml

some tailwind css files are missing from local preview

fix: missing tailwind styles on local preview

---

packages/ui/app/src/search/SearchV2.tsx
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v3.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/revalidate-all/v4.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/search/v2/facet.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/search/v2/key.ts
packages/ui/docs-bundle/src/pages/api/fern-docs/search/v2/reindex.ts
packages/ui/docs-bundle/src/server/queueAlgoliaReindex.ts
packages/ui/fern-docs-utils/src/constants.ts

fixes some issues based on real-world constraints:
- headers are not always forwarded (i.e. buildwithfern.com/learn) so we'll switch to using query parameters exclusively for search
- preview urls should trigger reindex
- qstash failures should be retried only once (3x is excessive, since the failures tend to be repetitive)
- don't return any ids in the reindex endpoint because it may include (and leak) data

fix: disable preview url indexing

---

packages/ui/components/src/kbd.scss
packages/ui/fern-docs-search-ui/src/components/desktop/desktop-search-button.tsx
packages/ui/fern-docs-search-ui/src/components/desktop/desktop-search-dialog.tsx
packages/ui/fern-docs-search-ui/src/components/ui/dropdown.tsx
packages/ui/fern-docs-search-ui/src/components/ui/tooltip.tsx

brighten the search box so that colored images don't affect text contrast.
----
Before:
After:
---
Before:
After:

fix: improve searchbar colors

---

packages/ui/components/src/CopyToClipboardButton.tsx
packages/ui/components/src/index.ts
packages/ui/fern-docs-syntax-highlighter/src/CodeBlockWithClipboardButton.tsx

fix: missing code block borders

---

packages/ui/docs-bundle/src/server/FernNextResponse.ts

Allow "open" redirects to domains ending with `.buildwithfern.com` to satisfy the edge case in WorkOS `redirect_uri` getting set to `app.buildwithfern.com` for `*.docs.buildwithfern.com` urls.

fix: allow .buildwithfern.com

---

packages/ui/app/src/mdx/components/accordion/index.scss
packages/ui/components/src/FernCard.scss

This PR fixes the list item display for both lists inside Cards and Accordions. 
Before:
After:

chore(docs): fix list item displays

---

packages/ui/docs-bundle/next.config.mjs
servers/fdr-deploy/scripts/fdr-deploy-stack.ts
servers/fdr/src/__test__/local/s3.test.ts
servers/fdr/src/__test__/mock.ts
servers/fdr/src/app/FdrConfig.ts
servers/fdr/src/services/s3/S3Service.ts

Server now points to the CDN when public docs are being accessed.
When docs are accessed internationally, it takes too long for the docs site to load (Singapore = ~3 seconds). With those clients hitting the CDN instead of buckets directly, that drops to ~ms.
Frontend server changes were tested locally, to make sure that hitting the CDN sped up the docs request. Server changes are not yet tested.

fix(docs): use cdn when loading docs from public s3 bucket

---

servers/fdr/src/services/s3/S3Service.ts

Fixes FER-3727
Duplicate https:// in url
Duplicate https:// in url

fix(docs): remove duplicate https from CDN url

---

packages/ui/fern-docs-edge-config/src/getFeatureFlags.ts

this lets us target `buildwithfern.com/learn` without accidentally targeting `*.docs.buildwithfern.com`

fix: more expressive feature flags

---

servers/fdr/src/services/algolia/AlgoliaService.ts

Fixes FER-
* Turns off v2 generation of records in favor of legacy v1 records
* Cost
* will test with dev FDR generations

chore: algolia service turn off v2

---

servers/fdr-deploy/scripts/fdr-deploy-stack.ts

Tested with locally running FDR docker instance

Setting NODE_ENV to sanitize outgoing error messages

---

packages/ui/fern-docs-server/src/ApiDefinitionLoader.ts

* API latest was short circuiting the api resolution too early
* Playground not loading during testing
* To be tested during FDR dev

fix api playground that was short circuiting too early

---

clis/generator-cli/src/cli.ts
clis/vercel-scripts/src/cli.ts
eslint.config.mjs
package.json
packages/fern-docs/bundle/src/server/xfernhost/node.ts
packages/fern-docs/bundle/turbo.json
packages/fern-docs/components/src/FontAwesomeIcon.tsx
packages/fern-docs/search-utils/src/SearchConfig.ts
packages/fern-docs/ui/turbo.json
packages/healthchecks/src/cli.ts
packages/healthchecks/src/getDocsURLs.ts
packages/scripts/src/cli.ts
pnpm-lock.yaml
servers/fdr/src/__test__/mock.ts
servers/fern-bot/turbo.json
turbo.json

fixes warning:
> Warning - the following environment variables are set on your Vercel project, but missing from "turbo.json". These variables WILL NOT be available to your application and may cause your build to fail. Learn more at https://turbo.build/repo/docs/platform-environment-variables
https://vercel.com/buildwithfern/app.buildwithfern.com/9cRftH7picr26Hm2fc525QipQK7L

fix: add env variabls to turbo

---

packages/fern-docs/ui/src/api-reference/ApiEndpointPage.tsx
packages/fern-docs/ui/src/api-reference/ApiReferencePage.tsx
packages/fern-docs/ui/src/changelog/ChangelogEntryPage.tsx
packages/fern-docs/ui/src/changelog/ChangelogPage.tsx
packages/fern-docs/ui/src/docs/DocsMainContent.tsx
packages/fern-docs/ui/src/docs/MarkdownPage.tsx
packages/fern-docs/ui/src/feedback/FeedbackPopover.tsx

FeedbackProvider ssr=false is causing the page to not load.

fix: ssr=true for feedback provider to avoid ssr issues on fern's docs

---

packages/fern-docs/bundle/src/app/api/fern-docs/auth/sso/callback/route.ts
packages/fern-docs/bundle/src/server/xfernhost/edge.ts

for some reason, in the middleware, headers.get("host") returns app.buildwithfern.com rather than the custom domain.

fix: workos redirect

---

packages/fern-docs/ui/src/layouts/GuideLayout.tsx
packages/fern-docs/ui/src/layouts/LayoutEvaluatorContent.tsx
packages/fern-docs/ui/src/layouts/OverviewLayout.tsx

This PR adds logic to respect the `hide-toc` property. 
Before:
After:

fix(docs): respect hide-toc frontmatter

---

packages/fern-docs/bundle/src/server/auth/ory.ts

This PR logs the token fetch request if the oauth callback fails. 
Cannot locally reproduce failed oauth token fetch. 
N/A

chore(docs): temporarily log request info on failed oauth2 callback

---

packages/fern-docs/ui/src/playground/utils/auth-headers.ts

If there is a header with the key `api_key`, the docs currently sends that as `ApiKey` when making a request. This PR updates the playground to send the correct wire value. 
Customer reported issue above. 
Preview URLs.

fix(playground): dont pascal case header key when making request

---

packages/fern-docs/bundle/.depcheckrc.json
packages/fern-docs/bundle/src/server/queue-reindex.ts

Reindexes for search v2 are throwing a 405 because qstash is using `POST` methods instead of `GET` methods. This PR updates the code to only use `GET` requests. 
Fixes failed search reindexes. 
Will be tested on merge.

fix(search): make sure that calls to the search endpoint are GET requests

---

packages/fern-docs/ui/src/analytics/CustomerAnalytics.tsx

Check for GA4 and GTM IDs from customer analytics config in addition to Vercel edge config.
Part of FER-3925
Manual testing in local dev

feat: Use GA4 and GTM IDs from customer analytics config

---

packages/fern-docs/search-ui/src/app/(demo)/api/suggest/route.ts
packages/fern-docs/search-ui/src/app/(demo)/search-demo.tsx

Uses Trieve instead of Algolia+LLM for AI suggestions.
Simplicity of query suggestions using Trieve's optimizations.
Manual QA in local dev testing environment. Used `?domain=docs.vapi.ai&provider=trieve&apiKey=tr-wTEWkjHW13qwm8dO7FuA8CeFM4fsNlhx&datasetId=8f44e302-3b53-4cfc-90f9-0065e91b821f&organizationId=483afda5-0b7d-4913-a52d-b0908c18e558` query params.

feat: use trieve for demo /api/suggest route

---

packages/fern-docs/ui/src/api-reference/ApiEndpointPage.tsx
packages/fern-docs/ui/src/api-reference/ApiReferencePage.tsx
packages/fern-docs/ui/src/api-reference/endpoints/Endpoint.tsx
packages/fern-docs/ui/src/api-reference/web-socket/WebSocket.tsx
packages/fern-docs/ui/src/api-reference/webhooks/Webhook.tsx
packages/fern-docs/ui/src/atoms/layout.ts
packages/fern-docs/ui/src/changelog/ChangelogPage.tsx
packages/fern-docs/ui/src/components/FernImage.tsx
packages/fern-docs/ui/src/contexts/api-page.ts
packages/fern-docs/ui/src/layouts/CustomLayout.tsx
packages/fern-docs/ui/src/layouts/GuideLayout.tsx
packages/fern-docs/ui/src/layouts/OverviewLayout.tsx
packages/fern-docs/ui/src/layouts/PageLayout.tsx
packages/fern-docs/ui/src/layouts/ReferenceLayout.tsx
packages/fern-docs/ui/src/mdx/components/html/index.tsx
packages/fern-docs/ui/src/search/SearchV2.tsx
packages/fern-docs/ui/src/sidebar/BuiltWithFern.tsx
packages/fern-docs/ui/src/themes/stylesheet/getLayoutVariables.ts

Update the image optimization widget inside of mdx to consider the maximum width of the layout that includes the image, and excludes SVGs and GIFs from optimization

fix: image optimization

---

packages/fern-docs/ui/src/components/FernImage.tsx
packages/fern-docs/ui/src/components/__test__/FernImage.test.ts
packages/fern-docs/ui/src/header/HeaderLogoImage.tsx
packages/fern-docs/ui/src/mdx/components/html/index.tsx
packages/fern-docs/ui/src/util/__test__/to-pixel-value.test.ts
packages/fern-docs/ui/src/util/to-pixel-value.ts

Fixes several issues that were introduced by https://github.com/fern-api/fern-platform/pull/1955 in which the width and height are misconfigured (and misses the point of srcsets).

fix: simplifies FernImage and fixes how it's contained within width/height

---

packages/parsers/package.json
packages/parsers/src/__test__/__snapshots__/openapi/cohere.json
packages/parsers/src/__test__/__snapshots__/openapi/deeptune.json
packages/parsers/src/__test__/__snapshots__/openapi/petstore.json
packages/parsers/src/__test__/__snapshots__/openapi/uploadcare.json
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/OneOfConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/SchemaConverter.node.ts
servers/fdr/src/__test__/local/services/api.test.ts
servers/fdr/src/__test__/local/util.ts
servers/fdr/src/controllers/api/getRegisterApiService.ts

Fixes a few specific pieces for the OpenApi Parser:
* Addresses anyOf (treats as oneOf), since both are expected to output a type of union
* Aligns ids from generated registration as opposed to using a randomly generated ID (fixes publish bug)
* Correctly cases pieces for subpackage metadata for slug generation and indexing
* Design partner bugfixes
* `fern docs dev` on design partner customer

fix: openapi parser design partner patches

---

pnpm-lock.yaml
servers/fdr/package.json
servers/fdr/tsconfig.json

* Adds the explicit types that generated TS code relies on (`@types/express-serve-static-core@0.4.19`) that was causing fdr to not compile
* Removes excluding compiling generated code that is necessary for FDR to run (https://github.com/fern-api/fern-platform/blob/6506692288b1102cea252a6fd3cc99afffe5b18a/servers/fdr/tsconfig.json)
* Updates pnpm lock
* FDR deployments have been broken for some time
* To be tested

fix: FDR generated code imports

---

packages/fern-docs/ui/src/playground/fetch-utils/executeProxyRest.ts
packages/workers/proxy/src/index.ts
packages/workers/proxy/wrangler.toml

Cloudflare tries to automatically optimize and compress the response from the proxy, which we'll attempt to avoid by setting `encodeBody="manual"`, which should give users a more realistic representation of the round-trip time it took to call the endpoint. Depending on where you are geographically, the proxy adds itself adds about 50ms-100ms of latency.
For requests where the `Content-Length` is known, we'll fetch and resolve the body inside the proxy's execution to measure the real round-trip time, and return that to the client.
The edge-case here is handling streaming (for endpoints with larger responses, like octet-stream, or SSE text streams), in which case it's impossible to know ahead of time how long it took to stream the entire content. As a result, we'll need to compute the time …

fix: add fallback logic for calculating proxy timing

---

packages/fern-docs/search-ui/src/components/shared/command-playground.tsx
packages/fern-docs/ui/src/playground/PlaygroundButton.tsx
packages/fern-docs/ui/src/playground/PlaygroundDrawer.tsx

This PR updates the naming of API Playground -> API Explorer for user-facing parts of the code base

chore(docs): playground -> explorer on user-facing things

---

packages/fdr-sdk/src/navigation/NodeCollector.ts
packages/fern-docs/search-server/src/turbopuffer/records/create-base-record.ts
packages/fern-docs/search-server/src/turbopuffer/records/create-turbopuffer-records.ts

Node IDs are getting duplicated (root cause is unclear so far) 
Unblock Turbopuffer indexing at a customer
Yes, locally tested

fix(ai): only index nodes with unique canonical slugs

---

packages/parsers/src/openrpc/1.x/MethodConverter.node.ts
packages/parsers/src/openrpc/1.x/OpenrpcDocumentConverter.node.ts
packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json
packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json
packages/parsers/src/openrpc/__test__/fixtures/ethereum/openrpc.json
packages/parsers/src/openrpc/utils/isReferenceObject.ts
packages/parsers/src/openrpc/utils/resolveContentDescriptorObject.ts
packages/parsers/src/openrpc/utils/resolveExample.ts
packages/parsers/src/openrpc/utils/resolveExamplePairing.ts
packages/parsers/src/openrpc/utils/resolveMethodReference.ts
packages/parsers/src/openrpc/utils/resolveReference.ts

This PR updates the openrpc parser to parse methods. 
Snapshot test

feat(openrpc): parse methods into fdr latest endpoints

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/guards/isWebhookDefinition.ts
packages/parsers/src/openapi/3.1/schemas/ObjectConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/__test__/ObjectConverter.node.test.ts
packages/parsers/src/openapi/3.1/schemas/primitives/StringConverter.node.ts
packages/parsers/src/openapi/__test__/__snapshots__/cohere.json
packages/parsers/src/openapi/__test__/__snapshots__/uploadcare.json
packages/parsers/src/openapi/__test__/fixtures/uploadcare/openapi.yml
packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json

* fixes pattern -> regex, min and max value plumbing for strings
* fixes webhook discrimination in parsing
* fixes object with only extra properties -> map type
* customer asks
* Snapshot and unit tests

fix: OpenApi Parser v2: Strings, Webhooks, Objects

---

packages/parsers/package.json
packages/parsers/src/openrpc/index.ts

Exports necessary classes from openrpc converter. 
Unblocks consumption in Fern CLI. 
N/A

fix(parsers): export OpenrpcContext and OpenrpcDocumentConverterNode

---

packages/fern-docs/cache/src/ApiDefinitionLoader.ts

If there is no `curl` snippet generated, the next.js backend will now generate one. 
As we add new parsers to the docs, this will automatically create cURL examples. 
Preview URLs

chore(snippets): generate curl snippets for api reference

---

packages/fern-docs/bundle/src/middleware.ts
packages/fern-docs/bundle/src/server/ld-adapter.ts
packages/fern-docs/edge-config/src/getLaunchDarklySettings.ts
packages/fern-docs/ui/src/atoms/types.ts
packages/fern-docs/ui/src/feature-flags/FeatureFlagProvider.tsx
packages/fern-docs/ui/src/feature-flags/LDFeatureFlagProvider.tsx

adds ability to pass in environments (relevant for launchdarkly's own docs)

feat: enable configuring custom environments for launchdarkly

---

fern/apis/fdr/definition/navigation/latest/__package__.yml
packages/fdr-sdk/src/client/generated/api/resources/navigation/resources/latest/types/FeatureFlagOptions.ts
packages/fern-docs/bundle/src/server/ld-adapter.ts
packages/fern-docs/ui/src/feature-flags/LDFeature.tsx
packages/fern-docs/ui/src/feature-flags/WithFeatureFlags.tsx
packages/fern-docs/ui/src/feature-flags/types.ts
packages/parsers/src/client/generated/api/resources/navigation/resources/latest/types/FeatureFlagOptions.ts
servers/fdr/src/api/generated/api/resources/navigation/resources/latest/types/FeatureFlagOptions.d.ts

based on feedback from launchdarkly the terminology is clearer to say "fallbackValue" than "default".
https://docs.launchdarkly.com/home/getting-started/vocabulary#fallback-value

break: rename default to fallbackValue for clarity

---

packages/fern-docs/bundle/src/server/ld-adapter.ts
packages/fern-docs/ui/src/atoms/types.ts
packages/fern-docs/ui/src/feature-flags/LDFeatureFlagProvider.tsx

- use a singleton to hopefully share _some_ resources between serverless function
- consume `x-secure-mode-hash` to validate the security of the server-generated flag
- disable diagnostics and events on the server-side
- disable non client-side flags (reduce payload, prevent leaking server-only flags(

fix: reduce the amount of data sent between ld server-side and ld client-side.

---

packages/fern-docs/local-preview-bundle/src/utils/getDocsPageProps.ts

For `apiV2` it would be great if the local preview showed curl examples. 
`fern docs dev` has a poor UX without these examples. 
Planning to test on dev.

fix(docs): preview bundle shows curl examples

---

packages/fdr-sdk/src/navigation/NodeCollector.ts
packages/parsers/src/openrpc/1.x/MethodConverter.node.ts
packages/parsers/src/openrpc/__test__/__snapshots__/ethereum.json
packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json
packages/parsers/src/openrpc/__test__/__snapshots__/solana.json
packages/parsers/src/openrpc/utils/resolveTags.ts

This PR updates the OpenRPC converter to respect the method name and any tag assigned to the method. 
- Customer requests asking to respect name
- Customer requests asking about nesting methods in resources
- Customer requests around showing authentication
Integration tests
**Note** also removing a log line from the node collector that is affecting print statements in the CLI @abvthecity

fix(openrpc): respect tags and name in openrpc

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openrpc/1.x/OpenrpcDocumentConverter.node.ts
packages/parsers/src/openrpc/__test__/__snapshots__/petstore.json
packages/parsers/src/utils/computeSubpackages.ts

This PR makes sure that OpenRPC conversion sets subpackages. A helper method is created from the OpenAPI parser. 
Allow users to use `tag` to configure API Reference layout. 
snapshot tests

fix(openrpc): set subpackages in fdr latest

---

servers/fdr/src/services/s3/S3Service.ts

Public S3 file uploads go through CDN. 
Performance when connecting from other regions (i.e. github actions). 
Will be tested on dev

fix(fdr): public s3 file uploads go through cloudfront

---

packages/fern-docs/ui/src/type-shorthand/index.tsx

* nullable was not showing up correctly in the api reference, now we make sure that it renders correctly
* customer demand

fix: ensure nullable shows in api reference

---

packages/fern-docs/components/src/accordion.scss
packages/fern-docs/search-ui/src/components/desktop/desktop.scss

safari's behavior for certain css rules is different from chrome. this fixes the following:
- `list-style-none` hides details > summary's arrow in chrome, but not safari. this PR hides it in safari too
- applying backdrop blur twice in nested div elements causes the entire graphics rendering to go bezerk in safari. This removes blur(40px) on the outer div:
before:
after:

fix: safari css behavior for accordion and backdrop blur

---

packages/fern-docs/bundle/package.json
packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts
pnpm-lock.yaml

Braintrust traced returns promise instead of raw object, requires await

---

CONTRIBUTING.md
packages/fern-docs/ui/src/playground/code-snippets/builders/python.ts

Fixes FER-3971
This corrects the file upload snippet which previously generated with a nested 'files' key.
See issue [here](https://github.com/fern-api/fern/issues/5563)
Yes -- generated Instabase incorrect endpoint with and without the fix.

fix: correct `python.ts` snippet generator for file uploads.

---

packages/fern-docs/ui/src/mdx/plugins/rehypeFernComponents.ts

```
Error: Expected component `Embed` to be defined: you likely forgot to import, pass, or provide it.
at l (eval at <anonymous> (/var/task/packages/fern-docs/bundle/.next/server/chunks/130.js:1:702), <anonymous>:18:313)
at p (eval at <anonymous> (/var/task/packages/fern-docs/bundle/.next/server/chunks/130.js:1:702), <anonymous>:3:950)
at m (eval at <anonymous> (/var/task/packages/fern-docs/bundle/.next/server/chunks/130.js:1:702), <anonymous>:18:286)
at Wc (/var/task/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
at Zc (/var/task/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
at Z …
```

fix: delete Embed which is crashing browser

---

packages/fern-docs/ui/src/header/HeaderLogoImage.tsx

fixes:
which regressed because of
https://github.com/fern-api/fern-platform/pull/2075

fix: width auto for logo

---

packages/fern-docs/components/src/FernButton.scss

chore: fix copy code styling

---

packages/fern-docs/bundle/src/app/api/fern-docs/search/v1/key/route.ts

Run the search/v1/key route in nodejs. Load with URL from S3 uses `crypto` which is not vercel edge friendly. 
Seeing 1k+ failures in search/v1/key. 
Previews

fix: run search/v1/apikey in node

---

packages/fern-docs/bundle/src/pages/api/fern-docs/revalidate-all/v3.ts

Increases revalidate batch size. Further reduce vercel cost and increase the performance of `fern generate --docs`
Building on recent architecture improvements. 
Preview.

feat: increase revalidate all concurrency to 500

---

packages/fern-docs/ui/src/playground/fetch-utils/requestToBodyInit.ts

Fixes FER-4155
We no longer stringify strings, leading to '\"string_val\"' as the final stringified request body.
TwelveLabs incident.
pnpm docs:dev

fix: do not stringify final values that are not explicitly set to `application/json` contentType

---

packages/fern-docs/ui/src/playground/endpoint/PlaygroundEndpointMultipartForm.tsx
packages/fern-docs/ui/src/playground/fetch-utils/requestToBodyInit.ts
packages/fern-docs/ui/src/playground/utils/default-values.ts
packages/fern-docs/ui/src/playground/utils/endpoints.ts

mirror same behavior as object properties for treating optional from data fields
- delete the entry when set to undefined
- add singular entries and add all entries from a dropdown

fix: handling optional fields in multipart form in the api playground

---

packages/fern-docs/ui/src/playground/endpoint/PlaygroundEndpoint.tsx
packages/fern-docs/ui/src/playground/fetch-utils/executeProxyRest.ts
packages/fern-docs/ui/src/playground/types/playgroundResponse.ts
packages/fern-docs/ui/src/playground/utils/oauth.ts

Fallback to returning a string response when response text cannot be JSON-ed.
Twelvelabs Incident.
Run on Twelvelabs broken SSE endpoint.

fix: fallback to string when response is not JSONable.

---

packages/parsers/package.json
packages/parsers/src/index.ts
packages/parsers/src/openapi/3.1/paths/request/RequestMediaTypeObjectConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/ReferenceConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/SchemaConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/BooleanConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/EnumConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/IntegerConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/NumberConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/StringConverter.node.ts
packages/parsers/src/openapi/__test__/__snapshots__/availability.json
packages/parsers/src/openapi/__test__/__snapshots__/cohere.json
packages/parsers/src/openapi/__test__/__snapshots__/nullable.json
packages/parsers/src/openapi/__test__/__snapshots__/only-include-referenced-schemas.json
packages/parsers/src/openapi/__test__/__snapshots__/openapi-filter.json
packages/parsers/src/openapi/__test__/__snapshots__/uploadcare.json

* adds correct enum default only for reference types
* adds null for example values if none found
* exports FDR types from package
* papercuts
* Snapshot tests

fix: OpenAPI parser v2 enum default for type reference

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/schemas/MixedSchemaConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/ReferenceConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/SchemaConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/__test__/SchemaConverter.node.test.ts
packages/parsers/src/openapi/3.1/schemas/primitives/BooleanConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/EnumConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/IntegerConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/NumberConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/primitives/StringConverter.node.ts

* fixes an issue where nullable was being rewritten by checking if `nullable` is set on the object
* now, we only set nullability if `nullable: false` if already set
* bugfix
* unit tests

fix: OpenApi Parser v2 thrashing nullable check

---

packages/fern-docs/ui/src/api-reference/endpoints/EndpointContentCodeSnippets.tsx

* Previously, we would check if there was more than one status code to render the cross product of status code x example. Now, we check the total number of examples instead to check if we should render a dropdown
* customer go live

fix: multiple responses even if only one response status code

---

packages/fern-docs/ui/src/api-reference/endpoints/useExampleSelection.ts

This PR adds a language fallback for example selection. If no example matches the currently selected language, always attempt to find a `curl` example before returning no examples. 
Fixes a bug reported by the Murf team.

fix: add language fallback for examples

---

packages/fern-docs/ui/src/search/SearchV2.tsx

This PR updates the behavior of how the search dialogue is opened so that the search button on medium-sized screens will function properly.
Before: 
https://github.com/user-attachments/assets/e4565370-6d79-4356-b8ad-27d27caecef5
After:
https://github.com/user-attachments/assets/ab72b5bd-e19d-42f1-a770-3893042796da

fix: link search button

---

fern/apis/fdr/definition/api/v1/read/type.yml
fern/apis/fdr/definition/api/v1/register/type.yml
packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/read/resources/type/types/FormDataBodyProperty.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/resources/type/types/FormDataBodyProperty.ts
packages/parsers/src/client/generated/api/resources/api/resources/v1/resources/read/resources/type/types/FormDataBodyProperty.ts
packages/parsers/src/client/generated/api/resources/api/resources/v1/resources/register/resources/type/types/FormDataBodyProperty.ts
servers/fdr/src/api/generated/api/resources/api/resources/v1/resources/read/resources/type/types/FormDataBodyProperty.d.ts
servers/fdr/src/api/generated/api/resources/api/resources/v1/resources/register/resources/type/types/FormDataBodyProperty.d.ts

Pipe through exploded through legacy API for the legacy OpenAPI parser. 
Snapshots.

fix: v1 api supports exploded

---

packages/fern-docs/ui/src/playground/endpoint/PlaygroundResponseCard.tsx

204 responses are not handled safely in the API plagyround. 
Customer reported issue. 
Local preview

chore: handle 204 content types in playground

---

packages/fern-docs/bundle/src/server/withInitialProps.ts
packages/fern-docs/bundle/src/server/withResolvedDocsContent.ts
packages/fern-docs/local-preview-bundle/src/utils/getDocsPageProps.ts
packages/fern-docs/ui/src/mdx/bundlers/mdx-bundler.ts
packages/fern-docs/ui/src/mdx/bundlers/next-mdx-remote.ts
packages/fern-docs/ui/src/mdx/plugins/rehype-files.ts
packages/fern-docs/ui/src/mdx/plugins/rehype-links.ts
packages/fern-docs/ui/src/mdx/types.ts

sometimes urls inside of markdown needs to be version-aware, so that when the same page is repeated in multiple versions, the docs writer can use an absolute path that works on all versions.
An example:
```mdx
[Link](/path/to/another/page)
```
and both the current page and the target page exists across multiple versions of the docs, then it will link you to the right version: `/version-a/path/to/another/page` and `/version-b/path/to/another/page` depending on which version you're currently viewing.

feat: resolve hrefs in markdown

---

packages/fern-docs/ui/src/atoms/location.ts

Remove console.debug line from console. 
Customer reported issue. 
N/A

fix: remove console.debug

---

packages/fern-docs/edge-config/src/getEdgeFlags.ts
packages/fern-docs/ui/src/services/useSearchService.ts
packages/fern-docs/utils/src/flags.ts

This PR hooks up a new Edge config to disable search. Makes it easier for customers like Deepgram to hijack search.

feat: search disabled config

---

servers/fdr-deploy/bin/fdr-deploy.ts

B/c load with url now loads from s3, we should be able to scale down FDR. 
Save some cost. 
N/A

chore: scale down initial fdr task nodes to 9

---

packages/fern-docs/syntax-highlighter/src/FernSyntaxHighlighter.tsx
packages/fern-docs/ui/src/mdx/components/code/CodeGroup.tsx
packages/fern-docs/ui/src/mdx/plugins/rehypeFernCode.ts

This PR introduces the ability to override the matching language for CodeBlocks:
https://github.com/user-attachments/assets/0249529a-c270-4d33-9d98-2a4930ef2b06
Usage is as follows:
````md
<CodeGroup>
```bash NPM matchLanguage="typescript"
npm install fern-api
```
```bash PyPI matchLanguage="python"
pypi install fern
```
</CodeGroup>
````

feat: override matching for code blocks

---

packages/fern-docs/search-server/src/turbopuffer/records/create-base-record.ts

Re 256 hash the turbopuffer record id. 
Limit max size of turbopuffer records. 
N/A

chore(docs): rehash turbopuffer record id

---

fern/apis/fdr/definition/api/latest/webhook.yml
packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/latest/resources/webhook/types/WebhookDefinition.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/client/Client.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/client/requests/RegisterApiDefinitionRequest.ts
packages/parsers/package.json
packages/parsers/src/client/generated/api/resources/api/resources/latest/resources/webhook/types/WebhookDefinition.ts
packages/parsers/src/openapi/3.1/auth/OAuth2SecuritySchemeConverter.node.ts
packages/parsers/src/openapi/3.1/guards/isWebhookDefinition.ts
packages/parsers/src/openapi/3.1/paths/OperationObjectConverter.node.ts
packages/parsers/src/openapi/3.1/paths/WebhooksObjectConverter.node.ts
packages/parsers/src/openapi/__test__/__snapshots__/webhooks.json
packages/parsers/src/openapi/__test__/fixtures/webhooks/openapi.yml
packages/parsers/src/openapi/utils/getEndpointId.ts
servers/fdr/src/api/generated/api/resources/api/resources/latest/resources/webhook/types/WebhookDefinition.d.ts

* Enables GET endpoints on webhooks
* Adds query parameters to FDR shape, for use with UI to display query parameters
* Customer request
* Snapshot tests

feat: Support GET webhooks OpenApi parser v2

---

packages/fern-docs/search-server/src/turbopuffer/records/create-markdown-records.ts

Fixes FER-
Markdown record ids need to be less than 64 bytes 
Failing to index records for a customer. Same issue as on the[ base record fixed in PR](https://github.com/fern-api/fern-platform/pull/2159)
@dsinghvi Any testing I need here?

fix: encode markdown record ids

---

fern/apis/fdr/definition/api/latest/__package__.yml
packages/fdr-sdk/src/api-definition/__test__/join.test.ts
packages/fdr-sdk/src/api-definition/__test__/prune.test.ts
packages/fdr-sdk/src/api-definition/join.ts
packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts
packages/fdr-sdk/src/api-definition/transformer.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/latest/types/ApiDefinition.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/client/Client.ts
packages/fdr-sdk/src/client/generated/api/resources/api/resources/v1/resources/register/client/requests/RegisterApiDefinitionRequest.ts
packages/fern-docs/cache/src/__test__/ApiDefinitionLoader.test.ts
packages/parsers/src/client/generated/api/resources/api/resources/latest/types/ApiDefinition.ts
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openrpc/1.x/OpenrpcDocumentConverter.node.ts
servers/fdr/src/api/generated/api/resources/api/resources/latest/types/ApiDefinition.d.ts
servers/fdr/src/controllers/api/getRegisterApiService.ts
servers/fdr/src/db/snippets/SnippetTemplate.ts

* Adds snippetsConfiguration to `ApiDefinitionLatest` payload, so that endpoints can be enriched with snippets
* Adds enrichment logic in registration step. Uses the same code paths as legacy `ApiDefinition`, so there should be little to no drift
* Sdk snippets for OpenApi v2 Parser customers
* To be tested with dev cli

chore: Add snippetsConfiguration to ApiDefinitionLatest

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openapi/3.1/paths/ServerObjectConverter.node.ts
packages/parsers/src/openapi/3.1/paths/__test__/ServerObjectConverter.node.test.ts

* fixes two papercuts from testing on customer specs:
1. server parsing with variables
2. webhook subpackage resolution when listing under webhooks
* customer tests
* unit tests and manual testing with cli

fix: OpenApi Parser v2 Server parsing logic and webhook subpackage resolution

---

packages/fern-docs/ui/src/themes/default/DefaultDocs.tsx
packages/fern-docs/ui/src/themes/default/index.scss

This PR fixes the behavior for mobile menu scrolling.
Before: 
https://github.com/user-attachments/assets/373b033b-0615-4090-8ae4-8905301d761e
After:
https://github.com/user-attachments/assets/ff8ea579-d1c0-4129-837e-a2756496969c

fix: sidebar behavior

---

packages/fern-docs/ui/src/api-reference/endpoints/EndpointRequestSection.tsx
packages/fern-docs/ui/src/api-reference/endpoints/EndpointResponseSection.tsx
packages/fern-docs/ui/src/api-reference/utils/__test__/maybeWrapTypeWithUndiscriminatedUnion.test.ts
packages/fern-docs/ui/src/api-reference/utils/maybeWrapTypeWithUndiscriminatedUnion.ts

* Adds support for displaying non-containing types as schemas underneath requests and responses if specified as such
* Customer requests
Unit tests and manually:

add undiscriminated union wrapper to various responses

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/auth/__test__/OAuth2SecuritySchemeConverter.node.test.ts
packages/parsers/src/openapi/3.1/auth/__test__/SecuritySchemeConverter.node.test.ts
packages/parsers/src/openapi/3.1/paths/__test__/OperationObjectConverter.node.test.ts
packages/parsers/src/openapi/3.1/paths/__test__/PathItemObjectConverter.node.test.ts
packages/parsers/src/openapi/__test__/__snapshots__/application-json.json
packages/parsers/src/openapi/__test__/__snapshots__/availability.json
packages/parsers/src/openapi/__test__/__snapshots__/cohere.json
packages/parsers/src/openapi/__test__/__snapshots__/content-type.json
packages/parsers/src/openapi/__test__/__snapshots__/deeptune.json
packages/parsers/src/openapi/__test__/__snapshots__/defaults.json
packages/parsers/src/openapi/__test__/__snapshots__/enum-casing.json
packages/parsers/src/openapi/__test__/__snapshots__/examples.json
packages/parsers/src/openapi/__test__/__snapshots__/inline-schema-reference.json
packages/parsers/src/openapi/__test__/__snapshots__/multi-url-generators-yml.json
packages/parsers/src/openapi/__test__/__snapshots__/nested-array-object.json
packages/parsers/src/openapi/__test__/__snapshots__/non-alphanumeric-characters.json
packages/parsers/src/openapi/__test__/__snapshots__/nullable.json
packages/parsers/src/openapi/__test__/__snapshots__/oauth.json
packages/parsers/src/openapi/__test__/__snapshots__/readonly.json
packages/parsers/src/openapi/__test__/__snapshots__/request-response-description.json
packages/parsers/src/openapi/__test__/__snapshots__/rules.json
packages/parsers/src/openapi/__test__/__snapshots__/x-fern-audiences.json
packages/parsers/src/openapi/utils/__test__/getEndpointId.test.ts
packages/parsers/src/openapi/utils/getEndpointId.ts
packages/parsers/src/utils/computeSubpackages.ts
servers/fdr/src/controllers/api/getRegisterApiService.ts

* Previously, we generated a new version of unique ids for endpoints, so that they were cleaner in the resulting payload. Now we generate the legacy apis
* Previously, we only tried to match on endpoint path -- upon closer inspection, it looks like the stringifying function appended an erroneous `/` and did not conform to the path parameter specification as in the table. Now we stringify properly, and use the legacy id to be more robust when matching
* Make sure that snippets properly match
*. To be tested with dev cli

fix: OpenApi Parser v2 Conform to legacy ids for snippet matching

---

packages/fern-docs/bundle/package.json
packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts
pnpm-lock.yaml
turbo.json

Fixes FER-4445
Added a `getErrorMessage` handler to the `streamText` result's `toDataStreamResponse`. The handler makes a best effort to identify the error kind and then logs an error message and posts to the #engineering-notifs slack channel.
Users and staff have noticed non-deterministic failures of the `Ask AI` feature where an reasonable prompt returns an empty response. This change will give us some idea of how frequently this issue is occurring.
**Local testing without Slack Token**
Ran locally with `pnpm docs:dev` and repro'd the bug. Confirmed that the response contained an error message with Log ID:
**Local testing with Slack Token**
- Slack message
- console log

[DRAFT] error handling and notification for AI search failures

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openapi/3.1/paths/ExampleObjectConverter.node.ts
packages/parsers/src/openapi/3.1/paths/parameters/ParameterBaseObjectConverter.node.ts
packages/parsers/src/openapi/__test__/__snapshots__/cohere.json
packages/parsers/src/openapi/__test__/__snapshots__/only-include-referenced-schemas.json
packages/parsers/src/openapi/__test__/__snapshots__/openapi-filter.json

* Quick patch to make sure that generated types are splayed in, not being gated on null check for other property
* Fine tooth comb analysis
* Live tests

fix: OpenAPI Parser v2 add generated types back in

---

packages/fern-docs/bundle/src/app/api/fern-docs/search/v2/chat/route.ts

FER-4458
Reduce the default topK number of docs inlined into the system prompt for Ask AI.
This is an attempt to mitigate the Bedrock throttling errors we've been seeing. See context in [slack thread](https://buildwithfern.slack.com/archives/C05E0S0A9SN/p1739894908205249?thread_ts=1739834073.265809&cid=C05E0S0A9SN)
Ran `pnpm docs:dev` locally and verified that Ask AI feature works as expected. Didn't try to invoke a throttling error since it should be less likely now (didn't occur after ~3 attempts).

docs/ask-ai: reduce max number of docs inlined in system prompt

---

packages/fern-docs/ui/src/hooks/useInterceptNextDataHref.ts

If we redirect to `/` or "" then we should make a request to `index.json`. 
Customer reported 404s on `/`
Local dev.

fix(docs): route to index.json

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/schemas/SchemaConverter.node.ts
packages/parsers/src/openapi/__test__/__snapshots__/pathing/warnings/single-element-type.txt
packages/parsers/src/openapi/__test__/__snapshots__/single-element-type.json
packages/parsers/src/openapi/__test__/fixtures/single-element-type/openapi.yml

* Previously, types that were single value arrays were not being parsed correctly. Now they are
* Customer spec review
* Fixture test

fix: OpenApi Parser v2 single element array types

---

servers/fdr/src/controllers/api/getRegisterApiService.ts

* Update snippet merging logic to only include when no snippets included 
* Only use python sync_client
* Discussion on more accurate snippets
* To be tested in FDR dev

fix: OpenAPI parser v2 more accurate example snippet merging

---

packages/fern-docs/mdx/package.json
packages/fern-docs/mdx/src/mdx-utils/extract-literal.ts
packages/fern-docs/mdx/src/parse.ts
packages/fern-docs/mdx/src/plugins/index.ts
packages/fern-docs/mdx/src/plugins/rehype-slug.ts
packages/fern-docs/mdx/src/toc.ts
packages/fern-docs/ui/package.json
packages/fern-docs/ui/src/components/table-of-contents/TableOfContents.tsx
packages/fern-docs/ui/src/mdx/bundlers/mdx-bundler.ts
packages/fern-docs/ui/src/mdx/bundlers/next-mdx-remote.ts
pnpm-lock.yaml

enables feature flags in the table of contents by scanning for feature flags and wrapping each table of content item with WithFeatureFlags

feat: implement feature flags in the table of contents

---

packages/parsers/package.json
packages/parsers/src/openapi/3.1/OpenApiDocumentConverter.node.ts
packages/parsers/src/openapi/3.1/paths/response/ResponseMediaTypeObjectConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/ComponentsConverter.node.ts
packages/parsers/src/openapi/3.1/schemas/__test__/ComponentsConverter.node.test.ts
packages/parsers/src/openapi/__test__/__snapshots__/oauth.json
packages/parsers/src/openapi/__test__/__snapshots__/x-fern-auth-variables.json

* Previously, auths were not propagating if there were no schemas. Now they do
* Customer edge case
* Snapshot test

fix: OpenApi Parser v2 return auths if types are nullish

---

packages/fern-docs/search-ui/src/components/desktop/desktop-ask-ai.tsx

Provide an `onError` handler to `useChat` that updates a bool atom. This state can then be used to show a useful error message rather than a blank response.
It's useful to show users a message rather than a blank response when an error occurs.
Tested locally: invoked an error and verified that the new error message was displayed.

docs/ask-ai: tell user to retry when error occurs

---

packages/fern-docs/ui/src/mdx/components/index.tsx
packages/fern-docs/ui/src/mdx/components/snippets/EndpointSchemaSnippet.tsx
packages/fern-docs/ui/src/mdx/components/snippets/index.ts
packages/fern-docs/ui/src/mdx/components/snippets/types.ts
packages/fern-docs/ui/src/mdx/components/snippets/useFindEndpoint.tsx
packages/fern-docs/ui/src/resolver/resolveMarkdownPage.ts

This PR sets up an alpha version of the `<EndpointSchemaSnippet />` component
**Not included:**
- Endpoint headers
- Endpoint errors (out of scope until this feature is requested)
- Selecting a specific property within a given schema shape

feat: schema snippet alpha

---

fern/apis/fdr/definition/navigation/latest/__package__.yml
fern/apis/fdr/definition/navigation/v1/__package__.yml
packages/fdr-sdk/src/client/generated/api/resources/navigation/resources/latest/types/PlaygroundSettings.ts
packages/fdr-sdk/src/client/generated/api/resources/navigation/resources/v1/types/PlaygroundSettings.ts
packages/fern-docs/ui/src/playground/PlaygroundButton.tsx
packages/parsers/src/client/generated/api/resources/navigation/resources/latest/types/PlaygroundSettings.ts
packages/parsers/src/client/generated/api/resources/navigation/resources/v1/types/PlaygroundSettings.ts
servers/fdr/src/api/generated/api/resources/navigation/resources/latest/types/PlaygroundSettings.d.ts
servers/fdr/src/api/generated/api/resources/navigation/resources/v1/types/PlaygroundSettings.d.ts

Add a `disabled` flag to the API Playgroud to start disabling the edge configuration. 
Deleting the `api-explorer-enabled` vercel storage config. 
N/A

feat(api): add flag to disable playground

---

packages/fern-docs/ui/src/atoms/location.ts
packages/fern-docs/ui/src/mdx/components/accordion/AccordionGroup.tsx

This PR updates the behavior of accordions, removing the anchor link when an accordion is closed. As a user, if I close an accordion, I do not expect the page location to still show me as navigating within that accordion. 
https://github.com/user-attachments/assets/e2bace78-7636-45f1-9773-df31e262d18c

feat: clear anchor on accordion close

---

packages/parsers/package.json
packages/parsers/src/openapi/utils/3.1/coalesceServers.ts
packages/parsers/src/openapi/utils/__test__/3.1/coalesceServers.test.ts

This PR ensure that we do not duplicate servers when coalescing.

fix: `coalesceServers` should only add new servers.

---

packages/fern-docs/ui/src/playground/WithLabel.tsx
packages/fern-docs/ui/src/playground/auth/PlaygroundOAuthForm.tsx

This PR resolves a visual bug where the `HelpCircle` icon (associated with parameter inputs in the Playground) were shrinking out of view.
Icon were previously disappearing when shrunk beyond a certain point. See thread [here](https://buildwithfern.slack.com/archives/C05E0S0A9SN/p1740411688660169)
Verified against Deepgram docs Playground:

fix: add `shrink-0` to `HelpCircle` icon.

---

packages/parsers/package.json

Follow-up to https://github.com/fern-api/fern-platform/pull/2212 so that the types required in the Fern CLI are aligned.

chore: Release @fern-api/docs-parser 0.0.65

---

packages/fdr-sdk/src/api-definition/migrators/v1ToV2.ts
servers/fdr/src/db/sdk/SdkDao.ts

This updates the `SdkDao` so that we surface the C# snippets written to the database (for consumption in the front-end).

fix(csharp): Read snippets from SdkDao

---

servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts

This wraps the `uploadToAlgoliaForRegistration` method in a `try-catch` that prevents docs hard failure when indexing fails.
Unblock Monite docs generation.
Will be testing!

fix: don't hard fail when Algolia Registration fails.

---

packages/fern-docs/ui/src/mdx/plugins/rehypeFernComponents.ts

Fixes rehypeFernComponents.ts to properly convert "a" nodes to "A" when containing images.

fix alias for a nodes in rehypeFernComponenets.ts

---

packages/fern-docs/ui/src/analytics/CustomerAnalytics.tsx
packages/fern-docs/ui/src/analytics/segment.ts

This PR removes Fern's Segment from all docs sites. 
Docs site without customer Segment integration: 
Docs site with customer Segment integration:

chore: remove fern segment

---

packages/fern-docs/ui/src/css/components.scss

- adds flex-wrap to property-header
https://buildwithfern.slack.com/archives/C0503TV6QLD/p1740930525291459
Manually

fix: added flex wrap

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/preview/route.ts
packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/serialize/route.ts
packages/fern-docs/bundle/src/components/shared-layout.tsx
packages/fern-docs/bundle/src/components/shared-page.tsx
packages/fern-docs/bundle/src/server/docs-loader.ts
packages/fern-docs/bundle/src/server/mdx-serializer.ts
packages/fern-docs/bundle/src/server/slack.ts

introduces a new route `/api/fern-docs/serialize` that serializes markdown in its own serverless function

fix: remote serializer

---

packages/fern-docs/bundle/src/components/playground/PlaygroundButton.tsx

Renames Play to Try it, even though @chdeskur still has to port over most of the API buttons.

chore: rename play to try it

---

clis/generator-cli/src/readme/ReadmeGenerator.ts

Fixes FER-
.NET developers usually don't have the nuget CLI installed and either install with the `dotnet` CLI or their IDE.

fix(csharp): Use dotnet CLI for nuget package install (readme)

---

packages/fern-docs/bundle/src/components/changelog/ChangelogContentLayout.tsx
packages/fern-docs/bundle/src/components/changelog/ChangelogEntryPage.tsx
packages/fern-docs/bundle/src/components/changelog/ChangelogPageClient.tsx
packages/fern-docs/bundle/src/components/layouts/index.scss

this pr: 
- preserves the sidebar on the changelog overview page
- removes the sidebar if a user clicks into a specific changelog pahge
- removes the sidebar if a user clicks to a changelog tab

feat: changelog formatting

---

packages/fern-docs/bundle/package.json
packages/fern-docs/bundle/src/components/api-reference/endpoints/EndpointContentCodeSnippets.tsx
packages/fern-docs/bundle/src/components/api-reference/webhooks/WebhookExample.tsx
packages/fern-docs/bundle/src/components/api-reference/websockets/WebSocket.tsx
packages/fern-docs/bundle/src/components/layouts/FooterLayout.tsx
packages/fern-docs/bundle/src/components/layouts/LayoutEvaluatorContent.tsx
packages/fern-docs/bundle/src/components/layouts/ReferenceLayout.tsx
packages/fern-docs/bundle/src/components/layouts/index.scss
packages/fern-docs/bundle/src/components/themes/cohere/index.scss
packages/fern-docs/bundle/src/components/themes/default/index.scss
packages/fern-docs/bundle/src/mdx/bundler/component.tsx
packages/fern-docs/bundle/src/mdx/components/prose.tsx
packages/fern-docs/bundle/src/mdx/components/steps/index.scss
pnpm-lock.yaml
tsconfig.json

Fixes FER-
- Added prose around steps
- Added styling so numbers in steps renders properly
- Issue with https://docs.frankieone.com/v2.0.0/docs/quickstart-guide/use-case-1-hosted-onesdk in canary
Manually

fix: aside component for guides

---

packages/fern-docs/bundle/src/server/docs-loader.ts

Fixes FER-4654
- Added a check for pruned endpoints
- Added default entry `https://host.com` if `environments` is empty
- Fix breaking docs when `servers` not defined in `openapi.json`
- tested locally

fix: add fallback url when `servers` is not defined

---

packages/fern-docs/bundle/src/server/docs-loader.ts

This PR resolves a conflict if both are true:
- `disable-header: true`
- `tabs-placement: header`

chore: set fallbacks for disable-header

---

packages/fern-docs/search-ui/src/components/shared/command-hits.tsx

This PR adds a boundary for the search hit tooltip.

chore: propose tooltip boundary

---

packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/@sidebar/[slug]/page.tsx
packages/fern-docs/bundle/src/app/[host]/[domain]/static/@sidebar/[slug]/page.tsx
packages/fern-docs/bundle/src/components/sidebar/nodes/SidebarRootNode.tsx

`root.id` is not the right node to pass into the node pruner. `the <Sidebar>` component is re-rendered on each page, so we're able to pass in the `currentNode.id` to the node pruner without adverse effects.

fix: resolve regression in hidden node pruning

---

packages/fern-docs/search-server/src/turbopuffer/to-documents.ts

hotfix: Feed LLM attributes.chunk instead of attributes.description

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/preview/route.ts

Reverts the `getHostEdge` fn in https://github.com/fern-api/fern-platform/commit/787da8d45d522ac233a94521de17649f56613850 because the _fern_preview_host is getting used to prevent previews after being set.

revert: preview url checks for hostname

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/changelog/route.ts
packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/llms-full.txt/route.ts
packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/llms.txt/route.ts

https://github.com/fern-api/fern-platform/pull/2386/files triggers the following 500-level error:
```
Cannot access nextUrl on the server. You cannot dot into a temporary client reference from a server component. You can only pass the value through to the client.
```
This is because `.nextUrl`, `.searchParams`, and `cookies()` cannot be contained within a `"use cache"` function. This PR breaks it up.

fix: use cache on routes

---

packages/fern-docs/bundle/src/components/login-button.tsx

this pr reformats the logout flow so it always calls our `/logout` endpoint

fix: logout flow

---

packages/fern-docs/bundle/src/server/xfernhost/util.test.ts
packages/fern-docs/bundle/src/server/xfernhost/util.ts

Handles x-fern-host if it is a comma delimited list. 
This is causing search indexing in algolia to fail. 
Unit tests.

chore(docs): fix algolia indexing issues

---

packages/fern-docs/bundle/src/components/playground/endpoint/PlaygroundResponseCard.tsx

This PR backports https://github.com/fern-api/fern-platform/pull/2251 to support 204 responses in the API playground. 
Customer asks. 
Previews.

chore: backport support for 204 responses

---

packages/fern-docs/bundle/src/server/xfernhost/util.test.ts
packages/fern-docs/bundle/src/server/xfernhost/util.ts

If for some reason, a comma-delimited list is forwarded to x-fern-host, we handle parsing this. This may happen due to proxies being added in x-forwarded-hosts. 
This broke search indexing for a customer b/c we failed to parse `x-fern-host` correctly. 
unit tests

chore: backport fix if `x-fern-host` is a comma delimited array

---

packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/@versionSelect/[slug]/page.tsx
packages/fern-docs/bundle/src/app/[host]/[domain]/static/@versionSelect/[slug]/page.tsx

Handles a semantic merge conflict to make linting green again.

chore: fix lint again

---

packages/fern-docs/bundle/src/mdx/bundler/serialize.ts

This PR removes `process.env` from mdx bundler. 
Security. 
Previews

chore(docs): restrict esbuild options in mdx bundler

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/oauth/webflow/callback/route.ts

this pr mirrors a change made yesterday on the pages router. required to move webflow to app router. 
does two things: 
- updates logs for clearer debugging
- moves the function off the edge runtime (-> node.js runtime)

backport: move webflow callback off edge runtime

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/oauth/webflow/callback/route.ts

this pr updates the webflow callback to redirect from staging to prod. allows us to avoid allowlisting staging environments.

chore: redirect webflow to prod

---

packages/fern-docs/bundle/src/components/feedback/FeedbackFormDialog.tsx
packages/fern-docs/bundle/src/components/feedback/FeedbackPopover.tsx

the background of the feedback modal should _always_ be solid.

fix: solid feedback background

---

packages/fern-docs/bundle/src/mdx/components/code/CodeGroup.tsx
packages/fern-docs/bundle/src/mdx/components/snippets/EndpointRequestSnippet.tsx
packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.test.ts
packages/fern-docs/bundle/src/mdx/plugins/rehype-code-block.ts

this pr backports a feature that allows the language sync between codeblocks to be overridden by any custom string
https://github.com/user-attachments/assets/d474a4ee-91bf-4747-a0f8-30cd3490ba70

backport: code sync override

---

packages/fern-docs/bundle/src/components/search.tsx

Fixes FER-
Point from app router to app router for /chat/ route (this was a custom rerouting done for elevenlabs to get around their proxy messing up text-streaming)
Remove dependency of app-router on page-router
Local

fix: Reroute from app.ferndocs to prod.ferndocs (app branch)

---

packages/fern-docs/bundle/src/app/[host]/[domain]/dynamic/@explorer/(..)explorer/@sidebar/[slug]/page.tsx
packages/fern-docs/bundle/src/app/[host]/[domain]/explorer/@sidebar/[slug]/page.tsx
packages/fern-docs/bundle/src/app/[host]/[domain]/static/@explorer/(..)explorer/@sidebar/[slug]/page.tsx

this pr adds a fallback for calculating the endpoints that should appear in the explorer sidebar. 
we first search for the endpoints assigned to the current version. if we can't filter to a version (e.g. the site is unversioned), we just use the root as context.

fix: add a fallback for the root

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/search/v2/reindex/algolia/route.ts
packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/search/v2/reindex/turbopuffer/route.ts
packages/fern-docs/bundle/src/server/docs-loader.ts
packages/fern-docs/bundle/src/server/file-resolver.ts
packages/fern-docs/bundle/src/server/mdx-serializer.ts
packages/fern-docs/bundle/src/server/rate-limiter.ts
packages/fern-docs/bundle/src/server/slack.ts

this pr limits the rate at which we receive notifications about various failures from `fern-platform` in the `#engineering-notifs` channel. currently, the quantity of error messages we get is overwhelming. 
as a follow-up, we need to add more context and address the root cause of some of these failures.

chore: limit notifications

---

packages/fern-docs/ui/src/search/SearchV2.tsx

Fixes FER-
Point from pages router to pages router for legacy AI chat deployments (mirror of: https://github.com/fern-api/fern-platform/pull/2451, see description)
Need to move from app. -> legacy.
Local

fix: Reroute from app.ferndocs to legacy.ferndocs (main branch)

---

servers/fdr/src/controllers/dashboard/getDashboardController.ts

bady copy/paste - `getDocsSitesForOrg` should check that the token is in the provided orgId (not in `"fern"`)

fix fdr org check in getDocsSitesForOrg

---

packages/fern-dashboard/next.config.ts
packages/fern-dashboard/src/lib/auth0.ts

`APP_BASE_URL` is not defined in `auth0.ts` (go to https://dashboard-dev.buildwithfern.com and log in to see the result)
Hoping this fixes

Rename APP_BASE_URL to NEXT_PUBLIC_APP_BASE_URL

---

packages/fern-dashboard/next.config.ts

https://github.com/fern-api/fern-platform/pull/2460 didn't work, trying more renames

Rename base env var to NEXT_PUBLIC_APP_BASE_URL

---

packages/fern-dashboard/src/lib/auth0.ts

https://github.com/fern-api/fern-platform/pull/2460 and https://github.com/fern-api/fern-platform/pull/2461, didn't work, trying this so that the env vars are stored as constants instead of `process.env`

Destructure process.env in auth0.ts

---

packages/fern-docs/bundle/src/app/[host]/[domain]/layout.tsx
packages/fern-docs/bundle/src/components/search.tsx
packages/fern-docs/bundle/src/state/search.tsx
packages/fern-docs/search-ui/src/components/desktop/desktop-search-button.tsx

improves placeholder for ai-enhanced search
this pr also updates the searchbar button to use `not-allowed` cursor when search is loading (e.g. in local preview mode)

chore: placeholder update

---

packages/commons/github/package.json
packages/fern-docs/bundle/package.json
pnpm-lock.yaml

Fixes FER-
Bumping versions up
Vanta alert & Dependabot alert
Checks

fix: Update octokit/dompurify versions to resolve dependabot alert

---

packages/fern-docs/bundle/src/components/header/HeaderContent.tsx
packages/fern-docs/bundle/src/components/header/HeaderTabsRoot.tsx
packages/fern-docs/bundle/src/components/sidebar/SidebarFixedItemsSection.tsx
packages/fern-docs/bundle/src/state/search.tsx

this pr updates the search placeholder to do two things:
- adjust to a slightly shorter title if in the sidebar
- hide overflow, for better ux on very small screens

chore: search placeholder updates

---

packages/fern-docs/bundle/src/state/search.tsx
packages/fern-docs/components/src/FernDropdown.scss
packages/fern-docs/components/src/FernTooltip.tsx
packages/fern-docs/search-ui/src/components/desktop/desktop-search-button.tsx

this pr adjusts the background of tooltips and dropdowns to ensure readability (especially within the API explorer)
this pr also slightly adjusts the prop construction of the searchbar button to resolve a warning
before: 
after:

chore: background blur

---

servers/fdr/src/controllers/docs/v2/getDocsWriteV2Service.ts

Adds conditional check to perform v1 indexing.
Indexing is currently recursive and may break on certain references.
Backport fix to `app` branch.

chore: conditionally disable v1 indexing.

---

packages/fern-docs/bundle/src/components/shared-layout.tsx
packages/fern-docs/bundle/src/server/file-resolver.ts

this pr removes slack notifications for the file resolver failure. rate limiting does not seem to be working, and the logging appears to cause timeouts for docs. 
fast-follow: to push a potential fix for the file caching issue

chore: remove slack notifs for file resolver

---

packages/fern-docs/ui/src/search/SearchV2.tsx

Fixes FER-
Reroute pages router /chat/ endpoint to use app router /chat/ endpoint
Will make it simpler (not requiring pushing to app and main branch for all AI chat)

fix: move page router to use prod.ferndocs

---

packages/fern-docs/bundle/src/components/PageActions.scss
packages/fern-docs/bundle/src/components/PageActionsDropdown.tsx
packages/fern-docs/bundle/src/components/PageHeader.tsx
packages/fern-docs/bundle/src/components/index.scss

chore: style page action button

---

packages/fern-docs/bundle/src/state/domain.ts
packages/fern-docs/bundle/src/state/playground.ts

Certain deployments dont want examples to be prepopulated in their docs. 
Even though the commits existed on the app router branch, these were removed. 
Preview URLs.

chore: disable examples for deployments on app router

---

packages/fern-docs/bundle/src/components/PageActionsDropdownOptions.tsx

- append .md to URL for LLM dropdown
- LLM has easy access to page content on the publicly-accessible .md pages
- previews

Append .md to URL for LLM dropdown

---

packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/llms-full.txt/route.ts
packages/fern-docs/bundle/src/app/[host]/[domain]/api/fern-docs/revalidate/route.ts

Caches `llms-full.txt` as part of reindex. 
Currently `llms-full.txt` will often time out and the idea here is to make sure that it is cached as soon as possible. 
Preview URLs

fix: reindex sets up cache for llms-full txt

---

packages/fern-docs/bundle/src/state/playground.ts

Allow certain customers to migrate to app router. 
Unblock app router. 
Preview URls.

fix: disable playground examples in certain conditions

---

packages/fern-docs/bundle/src/app/global-styles.tsx

this pr adds a fallback for the dark color theme if not specified in the user's docs.yml configuration. 
this handles an edge case where a site defines only light-mode but uses dark code blocks.

chore: add fallback for dark code

---

packages/fern-docs/bundle/src/mdx/bundler/serialize.ts

better handle cases with multiple twoslash codeblocks

chore: update twoslash nesting logic
